In [1]:
# =========================================
# REBUILD VERSION 2 - DATA GENERATION
# =========================================
import pandas as pd
import random
from pathlib import Path

random.seed(42)

project_root = Path("/Users/yizhen/Inventory_rebalancing_project")
raw_path = project_root / "data" / "raw"
raw_path.mkdir(parents=True, exist_ok=True)

print("project_root:", project_root)
print("raw_path:", raw_path)

project_root: /Users/yizhen/Inventory_rebalancing_project
raw_path: /Users/yizhen/Inventory_rebalancing_project/data/raw

In [3]:
# =========================================
# product_master. csv
# =========================================
import pandas as pd
import random

random.seed(42)

brand = "Ocean Spray"

# We want exactly 20 SKUs for 10oz
ten_oz_flavors = [
    "Cranberry",
    "Cranberry Grape",
    "Cranberry Apple",
    "White Cranberry",
    "Diet Cranberry",
    "Cranberry Pineapple",
    "Cranberry Mango",
    "Cranberry Raspberry",
    "Cranberry Cherry",
    "Cranberry Lemonade"
]

ten_oz_types = ["Juice", "Diet Juice"]
pack_types = ["Bottle", "Case"]

# Build 20 exact 10oz SKUs
ten_oz_rows = []
sku_counter = 1

for flavor in ten_oz_flavors:
    for ptype in ten_oz_types:
        sku_id = f"SKU{sku_counter:04d}"
        ten_oz_rows.append({
            "sku_id": sku_id,
            "sku_desc": f"{flavor} {ptype} 10oz Bottle",
            "brand": brand,
            "report_size": "10oz",
            "uom": "CASE",
            "product_type": ptype,
            "flavor": flavor,
            "pack_type": "Bottle",
            "shelf_life_days": 365 if ptype == "Juice" else 300,
            "is_active": "Y"
        })
        sku_counter += 1

ten_oz_df = pd.DataFrame(ten_oz_rows)
print("10oz SKU count:", len(ten_oz_df))
ten_oz_df.head()

10oz SKU count: 20

,sku_id,sku_desc,brand,report_size,uom,product_type,flavor,pack_type,shelf_life_days,is_active
0,SKU0001,Cranberry Juice 10oz Bottle,Ocean Spray,10oz,CASE,Juice,Cranberry,Bottle,365,Y
1,SKU0002,Cranberry Diet Juice 10oz Bottle,Ocean Spray,10oz,CASE,Diet Juice,Cranberry,Bottle,300,Y
2,SKU0003,Cranberry Grape Juice 10oz Bottle,Ocean Spray,10oz,CASE,Juice,Cranberry Grape,Bottle,365,Y
3,SKU0004,Cranberry Grape Diet Juice 10oz Bottle,Ocean Spray,10oz,CASE,Diet Juice,Cranberry Grape,Bottle,300,Y
4,SKU0005,Cranberry Apple Juice 10oz Bottle,Ocean Spray,10oz,CASE,Juice,Cranberry Apple,Bottle,365,Y

In [5]:
# =========================================
# generate 200 skus 
# =========================================
other_sizes = ["15.2oz", "64oz", "96oz"]
other_types = ["Juice", "Diet Juice", "Blend", "Cocktail"]
other_flavors = [
    "Cranberry",
    "Cranberry Grape",
    "Cranberry Apple",
    "White Cranberry",
    "Diet Cranberry",
    "Cranberry Pineapple",
    "Cranberry Mango",
    "Cranberry Raspberry",
    "Cranberry Cherry",
    "Cranberry Lemonade",
    "Ruby Cranberry",
    "Cran Tropical",
    "Cran Energy",
    "Cran Citrus",
    "Cranberry Peach"
]
other_pack_types = ["Bottle", "PET", "Case"]

rows = []

while len(rows) < 200:
    size = random.choice(other_sizes)
    ptype = random.choice(other_types)
    flavor = random.choice(other_flavors)
    pack = random.choice(other_pack_types)

    sku_id = f"SKU{sku_counter:04d}"
    sku_desc = f"{flavor} {ptype} {size} {pack}"

    if ptype == "Juice":
        shelf_life_days = 365
    elif ptype == "Diet Juice":
        shelf_life_days = 300
    elif ptype == "Blend":
        shelf_life_days = 270
    else:
        shelf_life_days = 365

    rows.append({
        "sku_id": sku_id,
        "sku_desc": sku_desc,
        "brand": brand,
        "report_size": size,
        "uom": "CASE",
        "product_type": ptype,
        "flavor": flavor,
        "pack_type": pack,
        "shelf_life_days": shelf_life_days,
        "is_active": random.choice(["Y", "Y", "Y", "Y", "N"])
    })
    sku_counter += 1

other_df = pd.DataFrame(rows)

product_master = pd.concat([ten_oz_df, other_df], ignore_index=True)

print("Total SKU count:", len(product_master))
print(product_master["report_size"].value_counts())
product_master.head()

Total SKU count: 220
report_size
15.2oz    72
96oz      70
64oz      58
10oz      20
Name: count, dtype: int64

,sku_id,sku_desc,brand,report_size,uom,product_type,flavor,pack_type,shelf_life_days,is_active
0,SKU0001,Cranberry Juice 10oz Bottle,Ocean Spray,10oz,CASE,Juice,Cranberry,Bottle,365,Y
1,SKU0002,Cranberry Diet Juice 10oz Bottle,Ocean Spray,10oz,CASE,Diet Juice,Cranberry,Bottle,300,Y
2,SKU0003,Cranberry Grape Juice 10oz Bottle,Ocean Spray,10oz,CASE,Juice,Cranberry Grape,Bottle,365,Y
3,SKU0004,Cranberry Grape Diet Juice 10oz Bottle,Ocean Spray,10oz,CASE,Diet Juice,Cranberry Grape,Bottle,300,Y
4,SKU0005,Cranberry Apple Juice 10oz Bottle,Ocean Spray,10oz,CASE,Juice,Cranberry Apple,Bottle,365,Y

In [7]:
# save csv files
product_master_file = raw_path / "product_master.csv"
product_master.to_csv(product_master_file, index=False)

print("Saved:", product_master_file)

Saved: /Users/yizhen/Inventory_rebalancing_project/data/raw/product_master.csv

In [9]:
# review 
print(product_master.shape)
print(product_master["report_size"].value_counts())
print(product_master.isnull().sum())

(220, 10)
report_size
15.2oz    72
96oz      70
64oz      58
10oz      20
Name: count, dtype: int64
sku_id             0
sku_desc           0
brand              0
report_size        0
uom                0
product_type       0
flavor             0
pack_type          0
shelf_life_days    0
is_active          0
dtype: int64

In [11]:
# 在 Python 里定义 Walmart 10oz 的 deployment 分组
ten_oz_skus = product_master.loc[
    product_master["report_size"] == "10oz", "sku_id"
].tolist()

print("10oz SKUs:", len(ten_oz_skus))

# 18 Walmart 10oz SKUs
walmart_10oz_skus = random.sample(ten_oz_skus, 18)

remaining = walmart_10oz_skus.copy()
random.shuffle(remaining)

healthy_skus = remaining[:5]
incoming_cover_skus = remaining[5:9]
rebalancing_skus = remaining[9:14]
true_risk_skus = remaining[14:18]

print("healthy:", healthy_skus)
print("incoming_cover:", incoming_cover_skus)
print("rebalancing:", rebalancing_skus)
print("true_risk:", true_risk_skus)

10oz SKUs: 20
healthy: ['SKU0002', 'SKU0016', 'SKU0015', 'SKU0011', 'SKU0003']
incoming_cover: ['SKU0005', 'SKU0017', 'SKU0019', 'SKU0013']
rebalancing: ['SKU0007', 'SKU0020', 'SKU0004', 'SKU0018', 'SKU0006']
true_risk: ['SKU0009', 'SKU0008', 'SKU0014', 'SKU0012']

In [13]:
# make a datframe for easy review
deployment_groups = pd.DataFrame({
    "sku_id": healthy_skus + incoming_cover_skus + rebalancing_skus + true_risk_skus,
    "deployment_group": (
        ["healthy"] * len(healthy_skus) +
        ["incoming_supply_cover"] * len(incoming_cover_skus) +
        ["rebalancing_needed"] * len(rebalancing_skus) +
        ["true_supply_risk"] * len(true_risk_skus)
    )
})

deployment_groups

     sku_id       deployment_group
0   SKU0002                healthy
1   SKU0016                healthy
2   SKU0015                healthy
3   SKU0011                healthy
4   SKU0003                healthy
5   SKU0005  incoming_supply_cover
6   SKU0017  incoming_supply_cover
7   SKU0019  incoming_supply_cover
8   SKU0013  incoming_supply_cover
9   SKU0007     rebalancing_needed
10  SKU0020     rebalancing_needed
11  SKU0004     rebalancing_needed
12  SKU0018     rebalancing_needed
13  SKU0006     rebalancing_needed
14  SKU0009       true_supply_risk
15  SKU0008       true_supply_risk
16  SKU0014       true_supply_risk
17  SKU0012       true_supply_risk

In [15]:
# rebuild weekly_fcst.csv
# 定义基础维度
dc_mapping = {
    "PA": "Pennsylvania DC",
    "TX": "Texas DC",
    "FL": "Florida DC",
    "NV": "Nevada DC",
    "WI": "Wisconsin DC",
    "WA": "Washington DC"
}

customers = ["Walmart", "Amazon", "Sam's", "Target", "Costco"]
forecast_weeks = [f"2026-W{str(i).zfill(2)}" for i in range(15, 27)]  # W15-W26

In [17]:
# 一个更可控的 forecast 生成规则: 这次我们让不同分组的 Walmart 10oz SKU 需求强度不同：
# healthy: 中等
# incoming_supply_cover: 中高
# rebalancing_needed: 高
# true_supply_risk: 高

# 同时对某些目标 DC 故意放大 demand，方便后面做 deployment。
def get_base_fcst_non_walmart(report_size):
    if report_size == "10oz":
        return random.randint(5000, 12000)
    elif report_size == "15.2oz":
        return random.randint(7000, 18000)
    elif report_size == "64oz":
        return random.randint(10000, 26000)
    else:
        return random.randint(9000, 22000)

def get_base_fcst_for_group(group_name):
    if group_name == "healthy":
        return random.randint(7000, 11000)
    elif group_name == "incoming_supply_cover":
        return random.randint(10000, 14000)
    elif group_name == "rebalancing_needed":
        return random.randint(12000, 18000)
    else:  # true_supply_risk
        return random.randint(13000, 19000)

customer_multiplier = {
    "Walmart": 1.15,
    "Amazon": 0.85,
    "Sam's": 1.00,
    "Target": 0.92,
    "Costco": 1.08
}

dc_multiplier = {
    "PA": 1.08,
    "TX": 1.05,
    "FL": 1.00,
    "NV": 0.95,
    "WI": 0.90,
    "WA": 0.88
}

In [19]:
#先定义 Walmart 18 个 SKU 的重点 DC 逻辑
# 这一步是为了后面 deployment：有些 rebalancing_needed SKU，让 PA 高库存、FL 低库存高需求 或者 PA 高库存、NV 极低库存高需求 先定义一个目标 DC map：
rebalancing_target_map = {}
for sku in rebalancing_skus:
    rebalancing_target_map[sku] = random.choice(["FL", "NV"])

true_risk_target_map = {}
for sku in true_risk_skus:
    true_risk_target_map[sku] = random.choice(["FL", "NV", "WA"])

print("rebalancing_target_map:", rebalancing_target_map)
print("true_risk_target_map:", true_risk_target_map)

rebalancing_target_map: {'SKU0007': 'NV', 'SKU0020': 'NV', 'SKU0004': 'NV', 'SKU0018': 'FL', 'SKU0006': 'FL'}
true_risk_target_map: {'SKU0009': 'NV', 'SKU0008': 'WA', 'SKU0014': 'FL', 'SKU0012': 'NV'}

In [21]:
# 生成fcst
rows = []

deployment_group_lookup = {
    **{sku: "healthy" for sku in healthy_skus},
    **{sku: "incoming_supply_cover" for sku in incoming_cover_skus},
    **{sku: "rebalancing_needed" for sku in rebalancing_skus},
    **{sku: "true_supply_risk" for sku in true_risk_skus},
}

for _, sku_row in product_master.iterrows():
    sku_id = sku_row["sku_id"]
    report_size = sku_row["report_size"]
    uom = sku_row["uom"]

    # Case 1: Walmart 10oz scoped SKUs
    if sku_id in walmart_10oz_skus:
        group_name = deployment_group_lookup[sku_id]
        assigned_customers = ["Walmart"]

        # add one optional secondary customer for realism
        if random.random() < 0.35:
            assigned_customers += random.sample(
                [c for c in customers if c != "Walmart"], 1
            )

        base_fcst = get_base_fcst_for_group(group_name)

        # assign DCs
        if group_name == "healthy":
            assigned_dcs = ["PA", "TX", "FL", "NV"]
        elif group_name == "incoming_supply_cover":
            assigned_dcs = ["PA", "FL", "NV", "WA"]
        elif group_name == "rebalancing_needed":
            target_dc = rebalancing_target_map[sku_id]
            donor_dc = "PA"
            assigned_dcs = list(set([donor_dc, target_dc, "TX", "WI"]))
        else:
            target_dc = true_risk_target_map[sku_id]
            assigned_dcs = list(set([target_dc, "FL", "WA", "TX"]))

        for customer in assigned_customers:
            for dc_id in assigned_dcs:
                dc_name = dc_mapping[dc_id]

                # base with customer + dc multiplier
                dc_base = base_fcst * customer_multiplier[customer] * dc_multiplier[dc_id]

                # make target DC demand higher for risk / deployment groups
                if group_name == "rebalancing_needed" and dc_id == rebalancing_target_map[sku_id]:
                    dc_base *= 1.35

                if group_name == "true_supply_risk" and dc_id == true_risk_target_map[sku_id]:
                    dc_base *= 1.40

                # donor PA sometimes a bit lower demand
                if group_name == "rebalancing_needed" and dc_id == "PA":
                    dc_base *= 0.85

                trend_type = random.choice(["flat", "up", "volatile"])

                for week_idx, forecast_week in enumerate(forecast_weeks):
                    if trend_type == "flat":
                        trend_factor = 1.0
                    elif trend_type == "up":
                        trend_factor = 1 + week_idx * 0.012
                    else:
                        trend_factor = random.uniform(0.93, 1.10)

                    noise = random.uniform(0.95, 1.06)
                    forecast_qty = int(dc_base * trend_factor * noise)

                    rows.append({
                        "forecast_week": forecast_week,
                        "sku_id": sku_id,
                        "dc_id": dc_id,
                        "dc_name": dc_name,
                        "customer": customer,
                        "uom": uom,
                        "forecast_qty": max(forecast_qty, 0)
                    })

    # Case 2: all other SKUs
    else:
        assigned_customers = random.sample(customers, k=random.choice([1, 2, 3]))
        base_fcst = get_base_fcst_non_walmart(report_size)

        for customer in assigned_customers:
            assigned_dcs = random.sample(list(dc_mapping.keys()), k=random.choice([2, 3, 4, 5]))

            for dc_id in assigned_dcs:
                dc_name = dc_mapping[dc_id]
                dc_base = base_fcst * customer_multiplier[customer] * dc_multiplier[dc_id]
                trend_type = random.choice(["flat", "up", "down", "volatile"])

                for week_idx, forecast_week in enumerate(forecast_weeks):
                    if trend_type == "flat":
                        trend_factor = 1.0
                    elif trend_type == "up":
                        trend_factor = 1 + week_idx * 0.010
                    elif trend_type == "down":
                        trend_factor = 1 - week_idx * 0.008
                    else:
                        trend_factor = random.uniform(0.92, 1.09)

                    noise = random.uniform(0.94, 1.07)
                    forecast_qty = int(dc_base * trend_factor * noise)

                    rows.append({
                        "forecast_week": forecast_week,
                        "sku_id": sku_id,
                        "dc_id": dc_id,
                        "dc_name": dc_name,
                        "customer": customer,
                        "uom": uom,
                        "forecast_qty": max(forecast_qty, 0)
                    })

weekly_forecast = pd.DataFrame(rows)
print("weekly_forecast shape:", weekly_forecast.shape)
weekly_forecast.head()

weekly_forecast shape: (18564, 7)

  forecast_week   sku_id dc_id        dc_name customer   uom  forecast_qty
0      2026-W15  SKU0001    WA  Washington DC   Target  CASE          4289
1      2026-W16  SKU0001    WA  Washington DC   Target  CASE          4036
2      2026-W17  SKU0001    WA  Washington DC   Target  CASE          4531
3      2026-W18  SKU0001    WA  Washington DC   Target  CASE          4487
4      2026-W19  SKU0001    WA  Washington DC   Target  CASE          4239

In [23]:
# 保存fcst
weekly_forecast_file = raw_path / "weekly_forecast.csv"
weekly_forecast.to_csv(weekly_forecast_file, index=False)

print("Saved:", weekly_forecast_file)

Saved: /Users/yizhen/Inventory_rebalancing_project/data/raw/weekly_forecast.csv

In [25]:
# review & check
walmart_10oz_review = weekly_forecast.merge(
    product_master[["sku_id", "report_size"]],
    on="sku_id",
    how="left"
)

walmart_10oz_scope = walmart_10oz_review[
    (walmart_10oz_review["customer"] == "Walmart") &
    (walmart_10oz_review["report_size"] == "10oz")
]

print("Walmart 10oz SKU count:", walmart_10oz_scope["sku_id"].nunique())
print(sorted(walmart_10oz_scope["sku_id"].unique()))

Walmart 10oz SKU count: 19
['SKU0001', 'SKU0002', 'SKU0003', 'SKU0004', 'SKU0005', 'SKU0006', 'SKU0007', 'SKU0008', 'SKU0009', 'SKU0011', 'SKU0012', 'SKU0013', 'SKU0014', 'SKU0015', 'SKU0016', 'SKU0017', 'SKU0018', 'SKU0019', 'SKU0020']

In [27]:
scope_summary = (
    walmart_10oz_scope
    .groupby(["sku_id", "dc_id"], as_index=False)
    .agg(avg_weekly_forecast=("forecast_qty", "mean"))
)

scope_summary.sort_values("avg_weekly_forecast", ascending=False).head(20)

     sku_id dc_id  avg_weekly_forecast
46  SKU0014    FL         31523.916667
19  SKU0006    FL         27286.250000
31  SKU0009    NV         24870.750000
29  SKU0008    WA         23395.916667
21  SKU0006    TX         23000.166667
39  SKU0012    NV         22904.083333
47  SKU0014    TX         22823.833333
69  SKU0020    NV         22209.583333
61  SKU0018    FL         21045.166667
11  SKU0004    NV         20864.166667
32  SKU0009    TX         20827.166667
28  SKU0008    TX         20332.750000
23  SKU0007    NV         19605.500000
27  SKU0008    FL         19459.250000
30  SKU0009    FL         19107.666667
48  SKU0014    WA         18878.750000
20  SKU0006    PA         18724.833333
22  SKU0006    WI         18432.666667
40  SKU0012    TX         18032.833333
38  SKU0012    FL         17288.333333

In [29]:
weekly_forecast["customer"].value_counts()

customer
Target     4332
Walmart    3804
Amazon     3732
Sam's      3444
Costco     3252
Name: count, dtype: int64

In [31]:
#rebuild inventory_snapshot.csv
import pandas as pd
import random

random.seed(42)

snapshot_date = "2026-04-10"

dc_mapping = {
    "PA": "Pennsylvania DC",
    "TX": "Texas DC",
    "FL": "Florida DC",
    "NV": "Nevada DC",
    "WI": "Wisconsin DC",
    "WA": "Washington DC"
}

# 先做一个 helper：从 forecast 里算未来4周平均周需求
forecast_4w = weekly_forecast[weekly_forecast["forecast_week"].isin(["2026-W15", "2026-W16", "2026-W17", "2026-W18"])].copy()

avg_fcst_4w = (
    forecast_4w
    .groupby(["sku_id", "dc_id"], as_index=False)
    .agg(avg_weekly_forecast_4w=("forecast_qty", "mean"))
)

# 为了后面查方便，转成 dict
fcst_lookup = {
    (row["sku_id"], row["dc_id"]): row["avg_weekly_forecast_4w"]
    for _, row in avg_fcst_4w.iterrows()
}

rows = []

for _, sku_row in product_master.iterrows():
    sku_id = sku_row["sku_id"]
    report_size = sku_row["report_size"]
    product_type = sku_row["product_type"]

    # 给普通SKU先一个基础库存倍数（相对 forecast）
    for dc_id, dc_name in dc_mapping.items():
        avg_fcst = fcst_lookup.get((sku_id, dc_id), 0)

        # 如果这个 SKU-DC 根本没有 forecast，就给一个小库存或零库存更真实
        if avg_fcst == 0:
            unrestricted_inventory = random.randint(0, 5000)
            blocked_inventory = int(unrestricted_inventory * random.uniform(0.00, 0.05))
            qi_inventory = int(unrestricted_inventory * random.uniform(0.00, 0.08))

            rows.append({
                "snapshot_date": snapshot_date,
                "dc_id": dc_id,
                "dc_name": dc_name,
                "sku_id": sku_id,
                "unrestricted_inventory": unrestricted_inventory,
                "blocked_inventory": blocked_inventory,
                "qi_inventory": qi_inventory
            })
            continue

        # 默认逻辑：普通SKU按 2.5~6 周库存
        target_wos = random.uniform(2.5, 6.0)

        # 对 Walmart 10oz 四类组做特别控制
        if sku_id in healthy_skus:
            # 全网大多健康，PA/TX 更高
            if dc_id in ["PA", "TX"]:
                target_wos = random.uniform(6.0, 10.0)
            else:
                target_wos = random.uniform(3.5, 6.5)

        elif sku_id in incoming_cover_skus:
            # 某些DC偏低，但不是极端低
            if dc_id in ["FL", "NV", "WA"]:
                target_wos = random.uniform(1.2, 2.0)
            else:
                target_wos = random.uniform(3.0, 5.5)

        elif sku_id in rebalancing_skus:
            target_dc = rebalancing_target_map[sku_id]

            # donor DC 固定给 PA
            if dc_id == "PA":
                target_wos = random.uniform(8.0, 13.0)
            elif dc_id == target_dc:
                target_wos = random.uniform(0.4, 1.2)
            elif dc_id in ["TX", "WI"]:
                target_wos = random.uniform(2.5, 4.5)
            else:
                target_wos = random.uniform(1.8, 3.5)

        elif sku_id in true_risk_skus:
            target_dc = true_risk_target_map[sku_id]

            # target DC 很低，全网其他 DC 也不算高
            if dc_id == target_dc:
                target_wos = random.uniform(0.2, 0.8)
            elif dc_id == "PA":
                target_wos = random.uniform(2.0, 3.5)
            else:
                target_wos = random.uniform(1.0, 2.5)

        else:
            # 其他非Walmart重点SKU：正常背景数据
            if dc_id in ["PA", "TX"]:
                target_wos = random.uniform(3.0, 6.0)
            else:
                target_wos = random.uniform(2.0, 5.0)

        unrestricted_inventory = int(avg_fcst * target_wos)

        # 增加一点随机波动
        unrestricted_inventory = int(unrestricted_inventory * random.uniform(0.95, 1.08))

        # blocked / qi 通常较小
        blocked_inventory = int(unrestricted_inventory * random.uniform(0.00, 0.06))
        qi_inventory = int(unrestricted_inventory * random.uniform(0.00, 0.10))

        rows.append({
            "snapshot_date": snapshot_date,
            "dc_id": dc_id,
            "dc_name": dc_name,
            "sku_id": sku_id,
            "unrestricted_inventory": max(unrestricted_inventory, 0),
            "blocked_inventory": max(blocked_inventory, 0),
            "qi_inventory": max(qi_inventory, 0)
        })

inventory_snapshot = pd.DataFrame(rows)

inventory_snapshot_file = raw_path / "inventory_snapshot.csv"
inventory_snapshot.to_csv(inventory_snapshot_file, index=False)

print("Saved:", inventory_snapshot_file)
print("Shape:", inventory_snapshot.shape)
inventory_snapshot.head()

Saved: /Users/yizhen/Inventory_rebalancing_project/data/raw/inventory_snapshot.csv
Shape: (1320, 7)

,snapshot_date,dc_id,dc_name,sku_id,unrestricted_inventory,blocked_inventory,qi_inventory
0,2026-04-10,PA,Pennsylvania DC,SKU0001,20949,280,1542
1,2026-04-10,TX,Texas DC,SKU0001,31028,785,92
2,2026-04-10,FL,Florida DC,SKU0001,16282,194,1058
3,2026-04-10,NV,Nevada DC,SKU0001,15875,770,10
4,2026-04-10,WI,Wisconsin DC,SKU0001,1307,45,35

In [33]:
#review & check WOS
inventory_review = inventory_snapshot.merge(
    avg_fcst_4w,
    on=["sku_id", "dc_id"],
    how="left"
)

inventory_review["avg_weekly_forecast_4w"] = inventory_review["avg_weekly_forecast_4w"].fillna(0)

inventory_review["est_wos"] = inventory_review.apply(
    lambda x: round(x["unrestricted_inventory"] / x["avg_weekly_forecast_4w"], 2)
    if x["avg_weekly_forecast_4w"] > 0 else None,
    axis=1
)

inventory_review.head()

,snapshot_date,dc_id,dc_name,sku_id,unrestricted_inventory,blocked_inventory,qi_inventory,avg_weekly_forecast_4w,est_wos
0,2026-04-10,PA,Pennsylvania DC,SKU0001,20949,280,1542,6911.250,3.03
1,2026-04-10,TX,Texas DC,SKU0001,31028,785,92,5686.375,5.46
2,2026-04-10,FL,Florida DC,SKU0001,16282,194,1058,4857.000,3.35
3,2026-04-10,NV,Nevada DC,SKU0001,15875,770,10,5810.750,2.73
4,2026-04-10,WI,Wisconsin DC,SKU0001,1307,45,35,0.000,NaN

In [35]:
# review & check WM 10oz
scope_inventory_review = inventory_review[inventory_review["sku_id"].isin(walmart_10oz_skus)].copy()

scope_inventory_review.sort_values(["sku_id", "dc_id"]).head(30)

,snapshot_date,dc_id,dc_name,sku_id,unrestricted_inventory,blocked_inventory,qi_inventory,avg_weekly_forecast_4w,est_wos
8,2026-04-10,FL,Florida DC,SKU0002,53310,146,1214,9782.500,5.45
9,2026-04-10,NV,Nevada DC,SKU0002,32880,199,913,8970.375,3.67
6,2026-04-10,PA,Pennsylvania DC,SKU0002,91533,4007,4908,10311.250,8.88
7,2026-04-10,TX,Texas DC,SKU0002,75090,3736,4644,9780.375,7.68
11,2026-04-10,WA,Washington DC,SKU0002,2187,76,119,0.000,NaN
10,2026-04-10,WI,Wisconsin DC,SKU0002,2988,24,84,0.000,NaN
14,2026-04-10,FL,Florida DC,SKU0003,35641,1721,1429,9195.000,3.88
15,2026-04-10,NV,Nevada DC,SKU0003,55171,2376,1173,8637.375,6.39
12,2026-04-10,PA,Pennsylvania DC,SKU0003,86161,1265,3982,9897.000,8.71
13,2026-04-10,TX,Texas DC,SKU0003,95201,1254,3087,9440.500,10.08
17,2026-04-10,WA,Washington DC,SKU0003,3758,26,41,0.000,NaN
16,2026-04-10,WI,Wisconsin DC,SKU0003,4089,80,299,0.000,NaN
20,2026-04-10,FL,Florida DC,SKU0004,898,6,11,0.000,NaN
21,2026-04-10,NV,Nevada DC,SKU0004,18297,654,856,20860.750,0.88
18,2026-04-10,PA,Pennsylvania DC,SKU0004,168879,4341,9854,15080.250,11.20
19,2026-04-10,TX,Texas DC,SKU0004,73420,2174,5548,16875.500,4.35
23,2026-04-10,WA,Washington DC,SKU0004,4398,165,270,0.000,NaN
22,2026-04-10,WI,Wisconsin DC,SKU0004,58061,2369,665,15011.000,3.87
26,2026-04-10,FL,Florida DC,SKU0005,14651,739,743,11055.250,1.33
27,2026-04-10,NV,Nevada DC,SKU0005,15118,864,1394,10386.625,1.46
24,2026-04-10,PA,Pennsylvania DC,SKU0005,43799,8,3162,12086.750,3.62
25,2026-04-10,TX,Texas DC,SKU0005,2157,104,131,0.000,NaN
29,2026-04-10,WA,Washington DC,SKU0005,15799,764,378,9833.375,1.61
28,2026-04-10,WI,Wisconsin DC,SKU0005,4,0,0,0.000,NaN
32,2026-04-10,FL,Florida DC,SKU0006,23182,1341,2153,27406.750,0.85
33,2026-04-10,NV,Nevada DC,SKU0006,1647,58,52,0.000,NaN
30,2026-04-10,PA,Pennsylvania DC,SKU0006,199243,8749,16258,19147.250,10.41
31,2026-04-10,TX,Texas DC,SKU0006,75992,3008,7195,22056.250,3.45
35,2026-04-10,WA,Washington DC,SKU0006,524,8,24,0.000,NaN
34,2026-04-10,WI,Wisconsin DC,SKU0006,65092,1763,1613,18790.000,3.46

In [37]:
# 检查 rebalancing SKU 场景
scope_inventory_review[
    scope_inventory_review["sku_id"].isin(rebalancing_skus)
].sort_values(["sku_id", "est_wos"], ascending=[True, False])

,snapshot_date,dc_id,dc_name,sku_id,unrestricted_inventory,blocked_inventory,qi_inventory,avg_weekly_forecast_4w,est_wos
18,2026-04-10,PA,Pennsylvania DC,SKU0004,168879,4341,9854,15080.250,11.20
19,2026-04-10,TX,Texas DC,SKU0004,73420,2174,5548,16875.500,4.35
22,2026-04-10,WI,Wisconsin DC,SKU0004,58061,2369,665,15011.000,3.87
21,2026-04-10,NV,Nevada DC,SKU0004,18297,654,856,20860.750,0.88
20,2026-04-10,FL,Florida DC,SKU0004,898,6,11,0.000,NaN
23,2026-04-10,WA,Washington DC,SKU0004,4398,165,270,0.000,NaN
30,2026-04-10,PA,Pennsylvania DC,SKU0006,199243,8749,16258,19147.250,10.41
34,2026-04-10,WI,Wisconsin DC,SKU0006,65092,1763,1613,18790.000,3.46
31,2026-04-10,TX,Texas DC,SKU0006,75992,3008,7195,22056.250,3.45
32,2026-04-10,FL,Florida DC,SKU0006,23182,1341,2153,27406.750,0.85
33,2026-04-10,NV,Nevada DC,SKU0006,1647,58,52,0.000,NaN
35,2026-04-10,WA,Washington DC,SKU0006,524,8,24,0.000,NaN
36,2026-04-10,PA,Pennsylvania DC,SKU0007,109912,4161,2516,12590.250,8.73
37,2026-04-10,TX,Texas DC,SKU0007,57377,819,3838,14177.250,4.05
40,2026-04-10,WI,Wisconsin DC,SKU0007,46777,1153,4040,12300.625,3.80
39,2026-04-10,NV,Nevada DC,SKU0007,14796,419,602,17508.625,0.85
38,2026-04-10,FL,Florida DC,SKU0007,1755,47,101,0.000,NaN
41,2026-04-10,WA,Washington DC,SKU0007,443,14,34,0.000,NaN
102,2026-04-10,PA,Pennsylvania DC,SKU0018,180168,6436,17116,14735.250,12.23
103,2026-04-10,TX,Texas DC,SKU0018,64343,1948,5344,16552.000,3.89
106,2026-04-10,WI,Wisconsin DC,SKU0018,48068,1268,3429,14122.750,3.40
104,2026-04-10,FL,Florida DC,SKU0018,24731,704,641,21139.750,1.17
105,2026-04-10,NV,Nevada DC,SKU0018,2025,85,44,0.000,NaN
107,2026-04-10,WA,Washington DC,SKU0018,1920,26,49,0.000,NaN
114,2026-04-10,PA,Pennsylvania DC,SKU0020,152835,4453,5943,14853.500,10.29
115,2026-04-10,TX,Texas DC,SKU0020,72128,3637,6632,16864.000,4.28
118,2026-04-10,WI,Wisconsin DC,SKU0020,45586,893,3470,14313.250,3.18
117,2026-04-10,NV,Nevada DC,SKU0020,9242,75,426,21205.750,0.44
116,2026-04-10,FL,Florida DC,SKU0020,4375,5,137,0.000,NaN
119,2026-04-10,WA,Washington DC,SKU0020,3105,43,236,0.000,NaN

In [39]:
# 检查 true risk SKU 场景
scope_inventory_review[
    scope_inventory_review["sku_id"].isin(true_risk_skus)
].sort_values(["sku_id", "est_wos"], ascending=[True, True])

,snapshot_date,dc_id,dc_name,sku_id,unrestricted_inventory,blocked_inventory,qi_inventory,avg_weekly_forecast_4w,est_wos
47,2026-04-10,WA,Washington DC,SKU0008,16022,466,342,23252.250,0.69
43,2026-04-10,TX,Texas DC,SKU0008,23165,745,324,20416.500,1.13
44,2026-04-10,FL,Florida DC,SKU0008,35460,160,2865,19680.250,1.80
42,2026-04-10,PA,Pennsylvania DC,SKU0008,806,2,46,0.000,NaN
45,2026-04-10,NV,Nevada DC,SKU0008,4508,22,235,0.000,NaN
46,2026-04-10,WI,Wisconsin DC,SKU0008,4428,185,343,0.000,NaN
51,2026-04-10,NV,Nevada DC,SKU0009,7208,318,43,22772.125,0.32
49,2026-04-10,TX,Texas DC,SKU0009,30473,1435,869,17954.000,1.70
50,2026-04-10,FL,Florida DC,SKU0009,38461,1527,1871,17447.750,2.20
53,2026-04-10,WA,Washington DC,SKU0009,32862,1894,263,14858.375,2.21
48,2026-04-10,PA,Pennsylvania DC,SKU0009,3285,148,43,0.000,NaN
52,2026-04-10,WI,Wisconsin DC,SKU0009,2569,7,120,0.000,NaN
69,2026-04-10,NV,Nevada DC,SKU0012,17549,878,1022,23157.250,0.76
67,2026-04-10,TX,Texas DC,SKU0012,19225,734,503,18209.750,1.06
68,2026-04-10,FL,Florida DC,SKU0012,31980,18,240,17402.250,1.84
71,2026-04-10,WA,Washington DC,SKU0012,39576,94,1416,15322.750,2.58
66,2026-04-10,PA,Pennsylvania DC,SKU0012,416,1,14,0.000,NaN
70,2026-04-10,WI,Wisconsin DC,SKU0012,1213,26,4,0.000,NaN
80,2026-04-10,FL,Florida DC,SKU0014,19985,610,1358,30231.000,0.66
83,2026-04-10,WA,Washington DC,SKU0014,21891,956,686,18708.250,1.17
79,2026-04-10,TX,Texas DC,SKU0014,31658,756,882,22905.500,1.38
78,2026-04-10,PA,Pennsylvania DC,SKU0014,3770,65,247,0.000,NaN
81,2026-04-10,NV,Nevada DC,SKU0014,4392,72,9,0.000,NaN
82,2026-04-10,WI,Wisconsin DC,SKU0014,2139,19,164,0.000,NaN

In [41]:
scope_inventory_review[
    scope_inventory_review["sku_id"].isin(rebalancing_skus)
].sort_values(["sku_id", "est_wos"], ascending=[True, False])

,snapshot_date,dc_id,dc_name,sku_id,unrestricted_inventory,blocked_inventory,qi_inventory,avg_weekly_forecast_4w,est_wos
18,2026-04-10,PA,Pennsylvania DC,SKU0004,168879,4341,9854,15080.250,11.20
19,2026-04-10,TX,Texas DC,SKU0004,73420,2174,5548,16875.500,4.35
22,2026-04-10,WI,Wisconsin DC,SKU0004,58061,2369,665,15011.000,3.87
21,2026-04-10,NV,Nevada DC,SKU0004,18297,654,856,20860.750,0.88
20,2026-04-10,FL,Florida DC,SKU0004,898,6,11,0.000,NaN
23,2026-04-10,WA,Washington DC,SKU0004,4398,165,270,0.000,NaN
30,2026-04-10,PA,Pennsylvania DC,SKU0006,199243,8749,16258,19147.250,10.41
34,2026-04-10,WI,Wisconsin DC,SKU0006,65092,1763,1613,18790.000,3.46
31,2026-04-10,TX,Texas DC,SKU0006,75992,3008,7195,22056.250,3.45
32,2026-04-10,FL,Florida DC,SKU0006,23182,1341,2153,27406.750,0.85
33,2026-04-10,NV,Nevada DC,SKU0006,1647,58,52,0.000,NaN
35,2026-04-10,WA,Washington DC,SKU0006,524,8,24,0.000,NaN
36,2026-04-10,PA,Pennsylvania DC,SKU0007,109912,4161,2516,12590.250,8.73
37,2026-04-10,TX,Texas DC,SKU0007,57377,819,3838,14177.250,4.05
40,2026-04-10,WI,Wisconsin DC,SKU0007,46777,1153,4040,12300.625,3.80
39,2026-04-10,NV,Nevada DC,SKU0007,14796,419,602,17508.625,0.85
38,2026-04-10,FL,Florida DC,SKU0007,1755,47,101,0.000,NaN
41,2026-04-10,WA,Washington DC,SKU0007,443,14,34,0.000,NaN
102,2026-04-10,PA,Pennsylvania DC,SKU0018,180168,6436,17116,14735.250,12.23
103,2026-04-10,TX,Texas DC,SKU0018,64343,1948,5344,16552.000,3.89
106,2026-04-10,WI,Wisconsin DC,SKU0018,48068,1268,3429,14122.750,3.40
104,2026-04-10,FL,Florida DC,SKU0018,24731,704,641,21139.750,1.17
105,2026-04-10,NV,Nevada DC,SKU0018,2025,85,44,0.000,NaN
107,2026-04-10,WA,Washington DC,SKU0018,1920,26,49,0.000,NaN
114,2026-04-10,PA,Pennsylvania DC,SKU0020,152835,4453,5943,14853.500,10.29
115,2026-04-10,TX,Texas DC,SKU0020,72128,3637,6632,16864.000,4.28
118,2026-04-10,WI,Wisconsin DC,SKU0020,45586,893,3470,14313.250,3.18
117,2026-04-10,NV,Nevada DC,SKU0020,9242,75,426,21205.750,0.44
116,2026-04-10,FL,Florida DC,SKU0020,4375,5,137,0.000,NaN
119,2026-04-10,WA,Washington DC,SKU0020,3105,43,236,0.000,NaN

In [43]:
scope_inventory_review[
    scope_inventory_review["sku_id"].isin(true_risk_skus)
].sort_values(["sku_id", "est_wos"], ascending=[True, True])

,snapshot_date,dc_id,dc_name,sku_id,unrestricted_inventory,blocked_inventory,qi_inventory,avg_weekly_forecast_4w,est_wos
47,2026-04-10,WA,Washington DC,SKU0008,16022,466,342,23252.250,0.69
43,2026-04-10,TX,Texas DC,SKU0008,23165,745,324,20416.500,1.13
44,2026-04-10,FL,Florida DC,SKU0008,35460,160,2865,19680.250,1.80
42,2026-04-10,PA,Pennsylvania DC,SKU0008,806,2,46,0.000,NaN
45,2026-04-10,NV,Nevada DC,SKU0008,4508,22,235,0.000,NaN
46,2026-04-10,WI,Wisconsin DC,SKU0008,4428,185,343,0.000,NaN
51,2026-04-10,NV,Nevada DC,SKU0009,7208,318,43,22772.125,0.32
49,2026-04-10,TX,Texas DC,SKU0009,30473,1435,869,17954.000,1.70
50,2026-04-10,FL,Florida DC,SKU0009,38461,1527,1871,17447.750,2.20
53,2026-04-10,WA,Washington DC,SKU0009,32862,1894,263,14858.375,2.21
48,2026-04-10,PA,Pennsylvania DC,SKU0009,3285,148,43,0.000,NaN
52,2026-04-10,WI,Wisconsin DC,SKU0009,2569,7,120,0.000,NaN
69,2026-04-10,NV,Nevada DC,SKU0012,17549,878,1022,23157.250,0.76
67,2026-04-10,TX,Texas DC,SKU0012,19225,734,503,18209.750,1.06
68,2026-04-10,FL,Florida DC,SKU0012,31980,18,240,17402.250,1.84
71,2026-04-10,WA,Washington DC,SKU0012,39576,94,1416,15322.750,2.58
66,2026-04-10,PA,Pennsylvania DC,SKU0012,416,1,14,0.000,NaN
70,2026-04-10,WI,Wisconsin DC,SKU0012,1213,26,4,0.000,NaN
80,2026-04-10,FL,Florida DC,SKU0014,19985,610,1358,30231.000,0.66
83,2026-04-10,WA,Washington DC,SKU0014,21891,956,686,18708.250,1.17
79,2026-04-10,TX,Texas DC,SKU0014,31658,756,882,22905.500,1.38
78,2026-04-10,PA,Pennsylvania DC,SKU0014,3770,65,247,0.000,NaN
81,2026-04-10,NV,Nevada DC,SKU0014,4392,72,9,0.000,NaN
82,2026-04-10,WI,Wisconsin DC,SKU0014,2139,19,164,0.000,NaN

In [45]:
scope_inventory_review[scope_inventory_review["est_wos"] < 2].shape

(26, 9)

In [47]:
# 定义 primary plant
import pandas as pd
import random

random.seed(42)

plant_state_map = {
    "LHV": "PA",
    "Henderson": "NV",
    "Sulphur": "TX"
}

plant_lines = {
    "LHV": ["L1", "L2", "L3"],
    "Henderson": ["H1", "H2", "H3"],
    "Sulphur": ["S1", "S2", "S3"]
}

production_weeks = [f"2026-W{str(i).zfill(2)}" for i in range(15, 27)]  # W15-W26
frozen_weeks = ["2026-W15", "2026-W16", "2026-W17", "2026-W18"]

In [49]:
# 给 SKU 分 primary plant
primary_plant_map = {}

for sku in product_master["sku_id"].tolist():
    # Rebalancing group
    if sku in rebalancing_skus:
        target_dc = rebalancing_target_map[sku]
        if target_dc == "NV":
            primary_plant_map[sku] = "Henderson"
        elif target_dc == "FL":
            primary_plant_map[sku] = random.choice(["LHV", "Sulphur"])
        else:
            primary_plant_map[sku] = random.choice(["LHV", "Sulphur", "Henderson"])

    # True risk group
    elif sku in true_risk_skus:
        target_dc = true_risk_target_map[sku]
        if target_dc == "NV":
            primary_plant_map[sku] = "Henderson"
        elif target_dc == "TX":
            primary_plant_map[sku] = "Sulphur"
        else:
            primary_plant_map[sku] = random.choice(["LHV", "Sulphur", "Henderson"])

    # Incoming cover group
    elif sku in incoming_cover_skus:
        primary_plant_map[sku] = random.choice(["LHV", "Sulphur", "Henderson"])

    # Healthy group
    elif sku in healthy_skus:
        primary_plant_map[sku] = random.choice(["LHV", "Sulphur", "Henderson"])

    # Other background SKUs
    else:
        primary_plant_map[sku] = random.choice(["LHV", "Sulphur", "Henderson"])

primary_plant_df = pd.DataFrame({
    "sku_id": list(primary_plant_map.keys()),
    "primary_plant": list(primary_plant_map.values())
})

primary_plant_df["plant_state"] = primary_plant_df["primary_plant"].map(plant_state_map)
primary_plant_df.head()

    sku_id primary_plant plant_state
0  SKU0001     Henderson          NV
1  SKU0002           LHV          PA
2  SKU0003           LHV          PA
3  SKU0004     Henderson          NV
4  SKU0005     Henderson          NV

In [51]:
# save
primary_plant_file = raw_path / "sku_plant_mapping.csv"
primary_plant_df.to_csv(primary_plant_file, index=False)
print("Saved:", primary_plant_file)

Saved: /Users/yizhen/Inventory_rebalancing_project/data/raw/sku_plant_mapping.csv

In [53]:
# 定义 cadence 规则 weekly /biweekly
cadence_map = {}

for sku in product_master["sku_id"].tolist():
    if sku in healthy_skus:
        cadence_map[sku] = random.choice(["weekly", "biweekly"])
    elif sku in incoming_cover_skus:
        cadence_map[sku] = random.choice(["biweekly", "monthly"])
    elif sku in rebalancing_skus:
        cadence_map[sku] = random.choice(["biweekly", "monthly"])
    elif sku in true_risk_skus:
        cadence_map[sku] = "monthly"
    else:
        cadence_map[sku] = random.choice(["weekly", "biweekly", "monthly"])

cadence_df = pd.DataFrame({
    "sku_id": list(cadence_map.keys()),
    "cadence": list(cadence_map.values())
})

cadence_df["cadence"].value_counts()

cadence
weekly      79
monthly     74
biweekly    67
Name: count, dtype: int64

In [55]:
#定义 base production qty
def get_base_production_qty(report_size, product_type):
    if report_size == "10oz":
        base = random.randint(30000, 90000)
    elif report_size == "15.2oz":
        base = random.randint(50000, 130000)
    elif report_size == "64oz":
        base = random.randint(70000, 180000)
    else:  # 96oz
        base = random.randint(60000, 160000)

    if product_type == "Juice":
        base *= 1.05
    elif product_type == "Diet Juice":
        base *= 0.90
    elif product_type == "Blend":
        base *= 1.00
    else:  # Cocktail
        base *= 0.95

    return int(base)

In [57]:
# 生成 production plan（核心）这一步会把 cadence 和 constraint 都写进去。
rows = []

product_lookup = product_master.set_index("sku_id").to_dict("index")

for sku in product_master["sku_id"].tolist():
    report_size = product_lookup[sku]["report_size"]
    product_type = product_lookup[sku]["product_type"]
    uom = product_lookup[sku]["uom"]

    plant_id = primary_plant_map[sku]
    plant_state = plant_state_map[plant_id]
    line = random.choice(plant_lines[plant_id])

    cadence = cadence_map[sku]
    base_qty = get_base_production_qty(report_size, product_type)

    # Decide which weeks this SKU produces
    if cadence == "weekly":
        active_weeks = production_weeks.copy()

    elif cadence == "biweekly":
        # choose one alternating pattern
        if random.random() < 0.5:
            active_weeks = ["2026-W15", "2026-W17", "2026-W19", "2026-W21", "2026-W23", "2026-W25"]
        else:
            active_weeks = ["2026-W16", "2026-W18", "2026-W20", "2026-W22", "2026-W24", "2026-W26"]

    else:  # monthly
        # choose one every-4-week pattern
        monthly_patterns = [
            ["2026-W15", "2026-W19", "2026-W23"],
            ["2026-W16", "2026-W20", "2026-W24"],
            ["2026-W17", "2026-W21", "2026-W25"],
            ["2026-W18", "2026-W22", "2026-W26"]
        ]
        active_weeks = random.choice(monthly_patterns)

    # Special constraints by deployment group
    # Healthy → normal supply
    # Incoming cover → at least one frozen-week production
    # Rebalancing → frozen production exists but often weaker or later
    # True risk → weak or no frozen production

    if sku in incoming_cover_skus:
        # ensure at least one frozen week is present
        if not any(w in frozen_weeks for w in active_weeks):
            active_weeks = active_weeks[:-1] + [random.choice(frozen_weeks)]

    if sku in rebalancing_skus:
        # make frozen support weaker overall
        pass

    if sku in true_risk_skus:
        # force frozen horizon to be weak or absent
        active_weeks = [w for w in active_weeks if w not in frozen_weeks]

        # if all removed, keep only week5+ production
        if len(active_weeks) == 0:
            active_weeks = ["2026-W19", "2026-W23"]

    for week in production_weeks:
        if week not in active_weeks:
            continue

        qty = base_qty

        # frozen vs non-frozen variability
        if week in frozen_weeks:
            variability = random.uniform(0.96, 1.04)
        else:
            variability = random.uniform(0.88, 1.12)

        qty = int(qty * variability)

        # Group-specific production strength
        if sku in healthy_skus:
            qty = int(qty * random.uniform(0.95, 1.08))

        elif sku in incoming_cover_skus:
            # enough to partially or mostly cover
            qty = int(qty * random.uniform(0.75, 0.95))

        elif sku in rebalancing_skus:
            # not zero, but not strong enough to rescue target DC in time
            if week in frozen_weeks:
                qty = int(qty * random.uniform(0.30, 0.55))
            else:
                qty = int(qty * random.uniform(0.65, 0.90))

        elif sku in true_risk_skus:
            # weak, and mostly outside frozen horizon
            if week in frozen_weeks:
                qty = int(qty * random.uniform(0.05, 0.20))
            else:
                qty = int(qty * random.uniform(0.35, 0.60))

        else:
            qty = int(qty * random.uniform(0.80, 1.05))

        # simulate line occupied / no extra capacity for certain true-risk NV cases
        if sku in true_risk_skus and plant_id == "Henderson" and week in frozen_weeks:
            qty = int(qty * random.uniform(0.00, 0.10))

        rows.append({
            "production_week": week,
            "plant_id": plant_id,
            "plant_state": plant_state,
            "sku_id": sku,
            "production_line": line,
            "planned_qty": max(qty, 0),
            "uom": uom
        })

production_plan = pd.DataFrame(rows)

production_plan_file = raw_path / "production_plan.csv"
production_plan.to_csv(production_plan_file, index=False)

print("Saved:", production_plan_file)
print("Shape:", production_plan.shape)
production_plan.head()

Saved: /Users/yizhen/Inventory_rebalancing_project/data/raw/production_plan.csv
Shape: (1568, 7)

,production_week,plant_id,plant_state,sku_id,production_line,planned_qty,uom
0,2026-W15,Henderson,NV,SKU0001,H2,33845,CASE
1,2026-W17,Henderson,NV,SKU0001,H2,33377,CASE
2,2026-W19,Henderson,NV,SKU0001,H2,31706,CASE
3,2026-W21,Henderson,NV,SKU0001,H2,24948,CASE
4,2026-W23,Henderson,NV,SKU0001,H2,38687,CASE

In [59]:
# 看 Walmart 10oz 重点 SKU 的 cadence
cadence_review = pd.DataFrame({
    "sku_id": walmart_10oz_skus,
    "cadence": [cadence_map[sku] for sku in walmart_10oz_skus],
    "group": [
        "healthy" if sku in healthy_skus else
        "incoming_supply_cover" if sku in incoming_cover_skus else
        "rebalancing_needed" if sku in rebalancing_skus else
        "true_supply_risk"
        for sku in walmart_10oz_skus
    ],
    "primary_plant": [primary_plant_map[sku] for sku in walmart_10oz_skus]
})

cadence_review.sort_values(["group", "sku_id"])

     sku_id   cadence                  group primary_plant
10  SKU0002  biweekly                healthy           LHV
3   SKU0003    weekly                healthy           LHV
9   SKU0011  biweekly                healthy           LHV
7   SKU0015    weekly                healthy     Henderson
2   SKU0016    weekly                healthy     Henderson
17  SKU0005   monthly  incoming_supply_cover     Henderson
8   SKU0013  biweekly  incoming_supply_cover     Henderson
11  SKU0017  biweekly  incoming_supply_cover     Henderson
0   SKU0019  biweekly  incoming_supply_cover     Henderson
13  SKU0004  biweekly     rebalancing_needed     Henderson
5   SKU0006   monthly     rebalancing_needed       Sulphur
6   SKU0007   monthly     rebalancing_needed     Henderson
4   SKU0018   monthly     rebalancing_needed           LHV
15  SKU0020  biweekly     rebalancing_needed     Henderson
14  SKU0008   monthly       true_supply_risk           LHV
16  SKU0009   monthly       true_supply_risk     Henderson
12  SKU0012   monthly       true_supply_risk     Henderson
1   SKU0014   monthly       true_supply_risk           LHV

In [61]:
# frozen 4 周 production support
frozen_prod = production_plan[
    production_plan["production_week"].isin(frozen_weeks)
].copy()

frozen_prod_summary = (
    frozen_prod
    .groupby("sku_id", as_index=False)
    .agg(frozen_4w_production_qty=("planned_qty", "sum"))
)

review_prod = cadence_review.merge(
    frozen_prod_summary,
    on="sku_id",
    how="left"
).fillna({"frozen_4w_production_qty": 0})

review_prod.sort_values(["group", "frozen_4w_production_qty"])

,sku_id,cadence,group,primary_plant,frozen_4w_production_qty
10,SKU0002,biweekly,healthy,LHV,122017.0
9,SKU0011,biweekly,healthy,LHV,159510.0
2,SKU0016,weekly,healthy,Henderson,206476.0
7,SKU0015,weekly,healthy,Henderson,306309.0
3,SKU0003,weekly,healthy,LHV,352775.0
17,SKU0005,monthly,incoming_supply_cover,Henderson,28174.0
8,SKU0013,biweekly,incoming_supply_cover,Henderson,91566.0
0,SKU0019,biweekly,incoming_supply_cover,Henderson,149229.0
11,SKU0017,biweekly,incoming_supply_cover,Henderson,149616.0
5,SKU0006,monthly,rebalancing_needed,Sulphur,15059.0
4,SKU0018,monthly,rebalancing_needed,LHV,18406.0
6,SKU0007,monthly,rebalancing_needed,Henderson,24384.0
15,SKU0020,biweekly,rebalancing_needed,Henderson,47013.0
13,SKU0004,biweekly,rebalancing_needed,Henderson,58846.0
1,SKU0014,monthly,true_supply_risk,LHV,0.0
12,SKU0012,monthly,true_supply_risk,Henderson,0.0
14,SKU0008,monthly,true_supply_risk,LHV,0.0
16,SKU0009,monthly,true_supply_risk,Henderson,0.0

In [63]:
# 特别检查 true_supply_risk
review_prod[review_prod["group"] == "true_supply_risk"].sort_values("frozen_4w_production_qty")

     sku_id  cadence             group primary_plant  frozen_4w_production_qty
1   SKU0014  monthly  true_supply_risk           LHV                       0.0
12  SKU0012  monthly  true_supply_risk     Henderson                       0.0
14  SKU0008  monthly  true_supply_risk           LHV                       0.0
16  SKU0009  monthly  true_supply_risk     Henderson                       0.0

In [65]:
# 特别检查 rebalancing_needed
review_prod[review_prod["group"] == "rebalancing_needed"].sort_values("frozen_4w_production_qty")

,sku_id,cadence,group,primary_plant,frozen_4w_production_qty
5,SKU0006,monthly,rebalancing_needed,Sulphur,15059.0
4,SKU0018,monthly,rebalancing_needed,LHV,18406.0
6,SKU0007,monthly,rebalancing_needed,Henderson,24384.0
15,SKU0020,biweekly,rebalancing_needed,Henderson,47013.0
13,SKU0004,biweekly,rebalancing_needed,Henderson,58846.0

In [67]:
# 生成STOreport
import pandas as pd
import random
from datetime import datetime, timedelta

random.seed(42)

rows = []

today = datetime(2026, 4, 10)

def random_date(start_days, end_days):
    return today + timedelta(days=random.randint(start_days, end_days))

for sku in walmart_10oz_skus:
    
    # -------- Covered by Incoming Supply --------
    if sku in incoming_cover_skus:
        target_dc = random.choice(["FL", "NV", "WA"])
        source_dc = "PA"

        shipment_qty = random.randint(20000, 60000)

        pgi_date = random_date(-2, 2)
        pgr_date = None  # still in transit
        should_deliver_date = random_date(2, 6)

        rows.append({
            "sku_id": sku,
            "from_node": source_dc,
            "to_node": target_dc,
            "shipment_qty": shipment_qty,
            "pgi_date": pgi_date.date(),
            "pgr_date": pgr_date,
            "should_deliver_date": should_deliver_date.date()
        })

    # -------- Rebalancing Needed --------
    elif sku in rebalancing_skus:
        # 故意不给 STO 或给很少
        if random.random() < 0.2:
            target_dc = rebalancing_target_map[sku]
            source_dc = "TX"

            shipment_qty = random.randint(5000, 15000)

            pgi_date = random_date(-3, 0)
            pgr_date = None
            should_deliver_date = random_date(5, 10)

            rows.append({
                "sku_id": sku,
                "from_node": source_dc,
                "to_node": target_dc,
                "shipment_qty": shipment_qty,
                "pgi_date": pgi_date.date(),
                "pgr_date": pgr_date,
                "should_deliver_date": should_deliver_date.date()
            })

    # -------- True Supply Risk --------
    elif sku in true_risk_skus:
        # 完全不给 STO
        continue

    # -------- Healthy --------
    elif sku in healthy_skus:
        if random.random() < 0.3:
            target_dc = random.choice(["FL", "NV"])
            source_dc = random.choice(["PA", "TX"])

            shipment_qty = random.randint(10000, 30000)

            pgi_date = random_date(-5, -1)
            pgr_date = None
            should_deliver_date = random_date(1, 4)

            rows.append({
                "sku_id": sku,
                "from_node": source_dc,
                "to_node": target_dc,
                "shipment_qty": shipment_qty,
                "pgi_date": pgi_date.date(),
                "pgr_date": pgr_date,
                "should_deliver_date": should_deliver_date.date()
            })

sto_df = pd.DataFrame(rows)

sto_file = raw_path / "sto_shipment_tracking.csv"
sto_df.to_csv(sto_file, index=False)

print("Saved:", sto_file)
sto_df.head()

Saved: /Users/yizhen/Inventory_rebalancing_project/data/raw/sto_shipment_tracking.csv

,sku_id,from_node,to_node,shipment_qty,pgi_date,pgr_date,should_deliver_date
0,SKU0019,PA,WA,27296,2026-04-08,None,2026-04-14
1,SKU0016,PA,FL,27870,2026-04-05,None,2026-04-14
2,SKU0003,PA,FL,17623,2026-04-09,None,2026-04-11
3,SKU0013,PA,NV,58618,2026-04-10,None,2026-04-12
4,SKU0002,TX,NV,19105,2026-04-06,None,2026-04-12

In [69]:
#STO review（非常重要） 看不同 group 是否符合预期
sto_df["sku_id"].isin(incoming_cover_skus).sum()
sto_df["sku_id"].isin(rebalancing_skus).sum()
sto_df["sku_id"].isin(true_risk_skus).sum()

0

In [71]:
print("Walmart 10oz SKUs:")
print(sorted(walmart_10oz_skus))

print("\nSTO SKUs:")
print(sorted(sto_df["sku_id"].unique()))

Walmart 10oz SKUs:
['SKU0002', 'SKU0003', 'SKU0004', 'SKU0005', 'SKU0006', 'SKU0007', 'SKU0008', 'SKU0009', 'SKU0011', 'SKU0012', 'SKU0013', 'SKU0014', 'SKU0015', 'SKU0016', 'SKU0017', 'SKU0018', 'SKU0019', 'SKU0020']

STO SKUs:
['SKU0002', 'SKU0003', 'SKU0004', 'SKU0005', 'SKU0013', 'SKU0016', 'SKU0017', 'SKU0019']

In [73]:
rows = []

today = datetime(2026, 4, 10)

def random_date(start_days, end_days):
    return today + timedelta(days=random.randint(start_days, end_days))

# 🔥只针对 Walmart 10oz SKU
for sku in walmart_10oz_skus:
    
    # -------- Incoming Supply Cover --------
    if sku in incoming_cover_skus:
        target_dc = random.choice(["FL", "NV", "WA"])
        source_dc = "PA"

        shipment_qty = random.randint(20000, 60000)

        rows.append({
            "sku_id": sku,
            "from_node": source_dc,
            "to_node": target_dc,
            "shipment_qty": shipment_qty,
            "pgi_date": random_date(-2, 2).date(),
            "pgr_date": None,
            "should_deliver_date": random_date(2, 6).date()
        })

    # -------- Rebalancing Needed --------
    elif sku in rebalancing_skus:
        # 大部分不给 STO
        if random.random() < 0.2:
            target_dc = rebalancing_target_map[sku]
            source_dc = "TX"

            rows.append({
                "sku_id": sku,
                "from_node": source_dc,
                "to_node": target_dc,
                "shipment_qty": random.randint(5000, 15000),
                "pgi_date": random_date(-3, 0).date(),
                "pgr_date": None,
                "should_deliver_date": random_date(5, 10).date()
            })

    # -------- True Risk --------
    elif sku in true_risk_skus:
        # 完全不给 STO
        continue

    # -------- Healthy --------
    elif sku in healthy_skus:
        if random.random() < 0.3:
            rows.append({
                "sku_id": sku,
                "from_node": random.choice(["PA", "TX"]),
                "to_node": random.choice(["FL", "NV"]),
                "shipment_qty": random.randint(10000, 30000),
                "pgi_date": random_date(-5, -1).date(),
                "pgr_date": None,
                "should_deliver_date": random_date(1, 4).date()
            })

sto_df = pd.DataFrame(rows)

sto_df.to_csv(raw_path / "sto_shipment_tracking.csv", index=False)

print("STO count:", len(sto_df))
sto_df.head()

STO count: 5

,sku_id,from_node,to_node,shipment_qty,pgi_date,pgr_date,should_deliver_date
0,SKU0019,PA,WA,39213,2026-04-12,None,2026-04-14
1,SKU0018,TX,FL,8733,2026-04-09,None,2026-04-15
2,SKU0013,PA,NV,43909,2026-04-09,None,2026-04-14
3,SKU0017,PA,WA,24679,2026-04-12,None,2026-04-13
4,SKU0005,PA,NV,44867,2026-04-10,None,2026-04-16

In [75]:
print("incoming_cover:", sto_df["sku_id"].isin(incoming_cover_skus).sum())
print("rebalancing:", sto_df["sku_id"].isin(rebalancing_skus).sum())
print("true_risk:", sto_df["sku_id"].isin(true_risk_skus).sum())

incoming_cover: 4
rebalancing: 1
true_risk: 0

In [81]:
!pip install duckdb

Requirement already satisfied: duckdb in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.5.1)

In [85]:
import sys
print(sys.executable)
print(sys.version)

/opt/anaconda3/bin/python
3.8.20 (default, Oct  3 2024, 10:25:41)
[Clang 14.0.6 ]

In [89]:
import sys
print(sys.executable)
print(sys.version)

/opt/anaconda3/bin/python
3.8.20 (default, Oct  3 2024, 10:25:41)
[Clang 14.0.6 ]

In [91]:
import sys
!{sys.executable} -m pip install --upgrade pip setuptools wheel
!{sys.executable} -m pip install duckdb==1.1.3

Requirement already satisfied: pip in /opt/anaconda3/lib/python3.8/site-packages (24.2)
Collecting pip
  Downloading pip-25.0.1-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.8/site-packages (75.1.0)
Collecting setuptools
  Using cached setuptools-75.3.4-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: wheel in /opt/anaconda3/lib/python3.8/site-packages (0.44.0)
Collecting wheel
  Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
Downloading pip-25.0.1-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 15.7 MB/s eta 0:00:00
Using cached setuptools-75.3.4-py3-none-any.whl (1.3 MB)
Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
Installing collected packages: wheel, setuptools, pip
  Attempting uninstall: wheel
    Found existing installation: wheel 0.44.0
    Uninstalling wheel-0.44.0:
      Successfully uninstalled wheel-0.44.0
  Attempting uninstall: setuptools
    Found existing installation: setuptools 75.1.0
    Uninstalling setuptools-75.1.0:
      Successfully uninstalled setuptools-75.1.0
  Attempting uninstall: pip
    Found existing installation: pip 24.2
    Uninstalling pip-24.2:
      Successfully uninstalled pip-24.2
Successfully installed pip-25.0.1 setuptools-75.3.4 wheel-0.45.1
Collecting duckdb==1.1.3
  Downloading duckdb-1.1.3-cp38-cp38-macosx_12_0_x86_64.whl.metadata (762 bytes)
Downloading duckdb-1.1.3-cp38-cp38-macosx_12_0_x86_64.whl (16.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 15.0 MB/s eta 0:00:00a 0:00:01
Installing collected packages: duckdb
Successfully installed duckdb-1.1.3

In [93]:
import duckdb
print(duckdb.__version__)

1.1.3

In [97]:
print("project_root =", project_root)
print("raw_path_str =", raw_path_str)

import os

files = [
    "product_master.csv",
    "inventory_snapshot.csv",
    "weekly_forecast.csv",
    "production_plan.csv",
    "sto_shipment_tracking.csv",
]

for f in files:
    full_path = os.path.join(raw_path_str, f)
    print(f, "exists =", os.path.exists(full_path), "| path =", full_path)

project_root = /Users/yizhen/Inventory_rebalancing_project
raw_path_str = /Users/yizhen/Inventory_rebalancing_project/data/raw
product_master.csv exists = True | path = /Users/yizhen/Inventory_rebalancing_project/data/raw/product_master.csv
inventory_snapshot.csv exists = True | path = /Users/yizhen/Inventory_rebalancing_project/data/raw/inventory_snapshot.csv
weekly_forecast.csv exists = True | path = /Users/yizhen/Inventory_rebalancing_project/data/raw/weekly_forecast.csv
production_plan.csv exists = True | path = /Users/yizhen/Inventory_rebalancing_project/data/raw/production_plan.csv
sto_shipment_tracking.csv exists = True | path = /Users/yizhen/Inventory_rebalancing_project/data/raw/sto_shipment_tracking.csv

In [105]:
db_file = str(project_root / "inventory_rebalancing_v2.duckdb")

In [107]:
con = duckdb.connect(db_file)
print("Connected.")

Connected.

In [109]:
import duckdb
import os

raw_path_str = str(raw_path)
db_file = str(project_root / "inventory_rebalancing_v2.duckdb")  # 🔥 改这里

con = duckdb.connect(db_file)

def load_table(table_name, file_name):
    full_path = os.path.join(raw_path_str, file_name)
    print(f"\nLoading {table_name} from {full_path}")
    con.execute(f"""
        CREATE OR REPLACE TABLE {table_name} AS
        SELECT * FROM read_csv_auto('{full_path}');
    """)
    print(f"Loaded {table_name} successfully.")

load_table("product_master", "product_master.csv")
load_table("inventory_snapshot", "inventory_snapshot.csv")
load_table("weekly_forecast", "weekly_forecast.csv")
load_table("production_plan", "production_plan.csv")
load_table("sto", "sto_shipment_tracking.csv")

print("All tables loaded.")

Loading product_master from /Users/yizhen/Inventory_rebalancing_project/data/raw/product_master.csv
Loaded product_master successfully.

Loading inventory_snapshot from /Users/yizhen/Inventory_rebalancing_project/data/raw/inventory_snapshot.csv
Loaded inventory_snapshot successfully.

Loading weekly_forecast from /Users/yizhen/Inventory_rebalancing_project/data/raw/weekly_forecast.csv
Loaded weekly_forecast successfully.

Loading production_plan from /Users/yizhen/Inventory_rebalancing_project/data/raw/production_plan.csv
Loaded production_plan successfully.

Loading sto from /Users/yizhen/Inventory_rebalancing_project/data/raw/sto_shipment_tracking.csv
Loaded sto successfully.
All tables loaded.

In [111]:
## ----------SQL Risk Model + Deployment Recommendation------------------
#定义scope
con.execute("""
CREATE OR REPLACE VIEW sku_scope AS
SELECT DISTINCT
    wf.sku_id,
    wf.customer,
    pm.report_size,
    pm.sku_desc,
    pm.uom
FROM weekly_forecast wf
JOIN product_master pm
    ON wf.sku_id = pm.sku_id
WHERE wf.customer = 'Walmart'
  AND pm.report_size = '10oz';
""")

In [113]:
con.sql("""
SELECT COUNT(DISTINCT sku_id) AS walmart_10oz_sku_count
FROM sku_scope
""").df()

   walmart_10oz_sku_count
0                      19

In [115]:
#算未来 4 周 demand
con.execute("""
CREATE OR REPLACE VIEW forecast_4w AS
SELECT
    wf.sku_id,
    wf.dc_id,
    wf.dc_name,
    wf.customer,
    wf.forecast_week,
    wf.forecast_qty
FROM weekly_forecast wf
JOIN sku_scope s
    ON wf.sku_id = s.sku_id
   AND wf.customer = s.customer
WHERE wf.forecast_week IN ('2026-W15','2026-W16','2026-W17','2026-W18');
""")

In [117]:
con.execute("""
CREATE OR REPLACE VIEW forecast_4w_summary AS
SELECT
    sku_id,
    dc_id,
    dc_name,
    customer,
    SUM(forecast_qty) AS forecast_4w_qty,
    AVG(forecast_qty) AS avg_weekly_forecast
FROM forecast_4w
GROUP BY sku_id, dc_id, dc_name, customer;
""")

In [119]:
con.execute("""
CREATE OR REPLACE VIEW inventory_wos AS
SELECT
    f.sku_id,
    f.dc_id,
    f.dc_name,
    f.customer,
    i.snapshot_date,
    i.unrestricted_inventory,
    i.blocked_inventory,
    i.qi_inventory,
    f.forecast_4w_qty,
    f.avg_weekly_forecast,
    CASE
        WHEN f.avg_weekly_forecast > 0
        THEN ROUND(i.unrestricted_inventory * 1.0 / f.avg_weekly_forecast, 2)
        ELSE NULL
    END AS wos
FROM forecast_4w_summary f
LEFT JOIN inventory_snapshot i
    ON f.sku_id = i.sku_id
   AND f.dc_id = i.dc_id;
""")

In [121]:
#先看 low WOS
con.sql("""
SELECT *
FROM inventory_wos
WHERE wos < 2
ORDER BY wos ASC
LIMIT 30
""").df()

,sku_id,dc_id,dc_name,customer,snapshot_date,unrestricted_inventory,blocked_inventory,qi_inventory,forecast_4w_qty,avg_weekly_forecast,wos
0,SKU0009,NV,Nevada DC,Walmart,2026-04-10,7208,318,43,101459.0,25364.75,0.28
1,SKU0020,NV,Nevada DC,Walmart,2026-04-10,9242,75,426,84823.0,21205.75,0.44
2,SKU0014,FL,Florida DC,Walmart,2026-04-10,19985,610,1358,120924.0,30231.00,0.66
3,SKU0008,WA,Washington DC,Walmart,2026-04-10,16022,466,342,93009.0,23252.25,0.69
4,SKU0012,NV,Nevada DC,Walmart,2026-04-10,17549,878,1022,92629.0,23157.25,0.76
5,SKU0007,NV,Nevada DC,Walmart,2026-04-10,14796,419,602,76489.0,19122.25,0.77
6,SKU0006,FL,Florida DC,Walmart,2026-04-10,23182,1341,2153,109627.0,27406.75,0.85
7,SKU0004,NV,Nevada DC,Walmart,2026-04-10,18297,654,856,83443.0,20860.75,0.88
8,SKU0012,TX,Texas DC,Walmart,2026-04-10,19225,734,503,72839.0,18209.75,1.06
9,SKU0005,FL,Florida DC,Walmart,2026-04-10,14651,739,743,51977.0,12994.25,1.13
10,SKU0008,TX,Texas DC,Walmart,2026-04-10,23165,745,324,81666.0,20416.50,1.13
11,SKU0014,WA,Washington DC,Walmart,2026-04-10,21891,956,686,74833.0,18708.25,1.17
12,SKU0018,FL,Florida DC,Walmart,2026-04-10,24731,704,641,84559.0,21139.75,1.17
13,SKU0017,WA,Washington DC,Walmart,2026-04-10,14071,716,642,46202.0,11550.50,1.22
14,SKU0005,NV,Nevada DC,Walmart,2026-04-10,15118,864,1394,47799.0,11949.75,1.27
15,SKU0019,NV,Nevada DC,Walmart,2026-04-10,19659,679,937,60775.0,15193.75,1.29
16,SKU0019,FL,Florida DC,Walmart,2026-04-10,21270,497,1637,64328.0,16082.00,1.32
17,SKU0014,TX,Texas DC,Walmart,2026-04-10,31658,756,882,91622.0,22905.50,1.38
18,SKU0005,WA,Washington DC,Walmart,2026-04-10,15799,764,378,44982.0,11245.50,1.40
19,SKU0009,TX,Texas DC,Walmart,2026-04-10,30473,1435,869,80168.0,20042.00,1.52
20,SKU0017,FL,Florida DC,Walmart,2026-04-10,23042,552,340,51941.0,12985.25,1.77
21,SKU0013,FL,Florida DC,Walmart,2026-04-10,21323,527,382,47645.0,11911.25,1.79
22,SKU0008,FL,Florida DC,Walmart,2026-04-10,35460,160,2865,78721.0,19680.25,1.80
23,SKU0013,NV,Nevada DC,Walmart,2026-04-10,21139,849,1553,46148.0,11537.00,1.83
24,SKU0012,FL,Florida DC,Walmart,2026-04-10,31980,18,240,69609.0,17402.25,1.84
25,SKU0019,WA,Washington DC,Walmart,2026-04-10,25955,1144,2076,54475.0,13618.75,1.91
26,SKU0009,FL,Florida DC,Walmart,2026-04-10,38461,1527,1871,78631.0,19657.75,1.96

In [123]:
#算 frozen production support
con.execute("""
CREATE OR REPLACE VIEW production_frozen_4w AS
SELECT
    sku_id,
    plant_id,
    plant_state,
    production_week,
    planned_qty
FROM production_plan
WHERE production_week IN ('2026-W15','2026-W16','2026-W17','2026-W18');
""")

In [125]:
# 汇总SKU
con.execute("""
CREATE OR REPLACE VIEW production_frozen_summary AS
SELECT
    sku_id,
    SUM(planned_qty) AS frozen_4w_production_qty
FROM production_frozen_4w
GROUP BY sku_id;
""")

In [127]:
# 再做一个“保守的 DC support 估算”。 因为 plant 产量不可能完整给每个 DC，我们先取 15% 作为潜在可分配量：
con.execute("""
CREATE OR REPLACE VIEW production_dc_support_est AS
SELECT
    sku_id,
    ROUND(frozen_4w_production_qty * 0.15, 0) AS est_dc_production_support
FROM production_frozen_summary;
""")

In [129]:
#算 STO inbound
con.execute("""
CREATE OR REPLACE VIEW sto_inbound_4w AS
SELECT
    sku_id,
    to_node AS dc_id,
    SUM(shipment_qty) AS inbound_sto_qty
FROM sto
WHERE pgr_date IS NULL
  AND should_deliver_date <= DATE '2026-05-08'
GROUP BY sku_id, to_node;
""")

In [131]:
# 找 donor DC 这个是 deployment 项目的关键。
# 我们定义 donor 条件： wos > 6 且 unrestricted_inventory - 2 * avg_weekly_forecast > 0
# 也就是这个 DC 自己很健康，并且有可转出的余量。
con.execute("""
CREATE OR REPLACE VIEW donor_candidates AS
SELECT
    sku_id,
    dc_id AS donor_dc,
    dc_name AS donor_dc_name,
    unrestricted_inventory,
    avg_weekly_forecast,
    wos,
    ROUND(unrestricted_inventory - 2 * avg_weekly_forecast, 0) AS donor_surplus_qty
FROM inventory_wos
WHERE wos > 6
  AND (unrestricted_inventory - 2 * avg_weekly_forecast) > 0;
""")

In [133]:
# 看一下donor
con.sql("""
SELECT *
FROM donor_candidates
ORDER BY sku_id, wos DESC
LIMIT 30
""").df()

,sku_id,donor_dc,donor_dc_name,unrestricted_inventory,avg_weekly_forecast,wos,donor_surplus_qty
0,SKU0002,PA,Pennsylvania DC,91533,11381.25,8.04,68771.0
1,SKU0002,TX,Texas DC,75090,10763.75,6.98,53563.0
2,SKU0003,TX,Texas DC,95201,11083.25,8.59,73035.0
3,SKU0003,PA,Pennsylvania DC,86161,11340.00,7.60,63481.0
4,SKU0004,PA,Pennsylvania DC,168879,15080.25,11.20,138719.0
5,SKU0006,PA,Pennsylvania DC,199243,19147.25,10.41,160949.0
6,SKU0007,PA,Pennsylvania DC,109912,13419.25,8.19,83074.0
7,SKU0011,TX,Texas DC,121360,12839.75,9.45,95681.0
8,SKU0011,PA,Pennsylvania DC,89560,13718.25,6.53,62124.0
9,SKU0015,PA,Pennsylvania DC,78103,11245.50,6.95,55612.0
10,SKU0016,TX,Texas DC,88981,9633.25,9.24,69715.0
11,SKU0016,PA,Pennsylvania DC,78585,9983.25,7.87,58619.0
12,SKU0016,NV,Nevada DC,56819,8517.75,6.67,39784.0
13,SKU0018,PA,Pennsylvania DC,180168,14735.25,12.23,150698.0
14,SKU0020,PA,Pennsylvania DC,152835,14853.50,10.29,123128.0

In [135]:
#先做最终风险分类
# 逻辑如下： Covered Risk wos < 2 且有 STO inbound
# 或 有 production support Rebalancing Opportunity wos < 2 没有 STO production support 也不够 但存在 donor DC True Supply Risk wos < 2 没有 STO production support 不够 也没有 donor DC

# 先建一个 donor flag：
con.execute("""
CREATE OR REPLACE VIEW donor_flag AS
SELECT
    sku_id,
    COUNT(*) AS donor_dc_count
FROM donor_candidates
GROUP BY sku_id;
""")

In [137]:
#最终风险表：
con.execute("""
CREATE OR REPLACE VIEW risk_final AS
SELECT
    i.sku_id,
    i.dc_id,
    i.dc_name,
    i.customer,
    i.unrestricted_inventory,
    i.avg_weekly_forecast,
    i.wos,
    COALESCE(s.inbound_sto_qty, 0) AS inbound_sto_qty,
    COALESCE(p.est_dc_production_support, 0) AS est_dc_production_support,
    COALESCE(d.donor_dc_count, 0) AS donor_dc_count,

    CASE
        WHEN i.wos >= 2 THEN 'Healthy'

        WHEN i.wos < 2
             AND COALESCE(s.inbound_sto_qty, 0) >= i.avg_weekly_forecast
        THEN 'Covered Risk'

        WHEN i.wos < 2
             AND COALESCE(p.est_dc_production_support, 0) >= i.avg_weekly_forecast
        THEN 'Covered Risk'

        WHEN i.wos < 2
             AND COALESCE(d.donor_dc_count, 0) > 0
        THEN 'Rebalancing Opportunity'

        ELSE 'True Supply Risk'
    END AS final_risk
FROM inventory_wos i
LEFT JOIN sto_inbound_4w s
    ON i.sku_id = s.sku_id
   AND i.dc_id = s.dc_id
LEFT JOIN production_dc_support_est p
    ON i.sku_id = p.sku_id
LEFT JOIN donor_flag d
    ON i.sku_id = d.sku_id;
""")

In [139]:
# 看分类结果
con.sql("""
SELECT
    final_risk,
    COUNT(*) AS cnt
FROM risk_final
GROUP BY final_risk
ORDER BY cnt DESC
""").df()

                final_risk  cnt
0                  Healthy   46
1         True Supply Risk   14
2             Covered Risk    8
3  Rebalancing Opportunity    5

In [141]:
# 做 deployment recommendation
# 我们先简单做法： 对每个 sku_id，选 wos 最高的 donor DC。
con.execute("""
CREATE OR REPLACE VIEW best_donor AS
SELECT *
FROM (
    SELECT
        sku_id,
        donor_dc,
        donor_dc_name,
        donor_surplus_qty,
        wos,
        ROW_NUMBER() OVER (
            PARTITION BY sku_id
            ORDER BY wos DESC, donor_surplus_qty DESC
        ) AS rn
    FROM donor_candidates
) t
WHERE rn = 1;
""")

In [143]:
# 输出 recommendation：
con.execute("""
CREATE OR REPLACE VIEW deployment_recommendation AS
SELECT
    r.sku_id,
    r.dc_id AS shortage_dc,
    r.dc_name AS shortage_dc_name,
    r.wos AS shortage_wos,
    r.unrestricted_inventory,
    r.avg_weekly_forecast,
    ROUND(2 * r.avg_weekly_forecast - r.unrestricted_inventory, 0) AS recommended_transfer_qty,
    b.donor_dc,
    b.donor_dc_name,
    b.donor_surplus_qty,
    r.final_risk,
    CASE
        WHEN r.final_risk = 'Rebalancing Opportunity'
        THEN 'Transfer inventory from donor DC to shortage DC'
        WHEN r.final_risk = 'Covered Risk'
        THEN 'Monitor inbound supply / production'
        WHEN r.final_risk = 'True Supply Risk'
        THEN 'Escalate to planner: no feasible donor within network'
        ELSE 'No action required'
    END AS recommendation
FROM risk_final r
LEFT JOIN best_donor b
    ON r.sku_id = b.sku_id
WHERE r.final_risk IN ('Rebalancing Opportunity', 'Covered Risk', 'True Supply Risk');
""")

In [145]:
# 看结果
con.sql("""
SELECT *
FROM deployment_recommendation
ORDER BY
    CASE final_risk
        WHEN 'True Supply Risk' THEN 1
        WHEN 'Rebalancing Opportunity' THEN 2
        WHEN 'Covered Risk' THEN 3
        ELSE 4
    END,
    shortage_wos ASC
LIMIT 50
""").df()

,sku_id,shortage_dc,shortage_dc_name,shortage_wos,unrestricted_inventory,avg_weekly_forecast,recommended_transfer_qty,donor_dc,donor_dc_name,donor_surplus_qty,final_risk,recommendation
0,SKU0009,NV,Nevada DC,0.28,7208,25364.75,43522.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
1,SKU0014,FL,Florida DC,0.66,19985,30231.00,40477.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
2,SKU0008,WA,Washington DC,0.69,16022,23252.25,30483.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
3,SKU0012,NV,Nevada DC,0.76,17549,23157.25,28766.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
4,SKU0012,TX,Texas DC,1.06,19225,18209.75,17195.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
5,SKU0005,FL,Florida DC,1.13,14651,12994.25,11338.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
6,SKU0008,TX,Texas DC,1.13,23165,20416.50,17668.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
7,SKU0014,WA,Washington DC,1.17,21891,18708.25,15526.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
8,SKU0014,TX,Texas DC,1.38,31658,22905.50,14153.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
9,SKU0005,WA,Washington DC,1.40,15799,11245.50,6692.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
10,SKU0009,TX,Texas DC,1.52,30473,20042.00,9611.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
11,SKU0008,FL,Florida DC,1.80,35460,19680.25,3901.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
12,SKU0012,FL,Florida DC,1.84,31980,17402.25,2825.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
13,SKU0009,FL,Florida DC,1.96,38461,19657.75,855.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
14,SKU0020,NV,Nevada DC,0.44,9242,21205.75,33170.0,PA,Pennsylvania DC,123128.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
15,SKU0007,NV,Nevada DC,0.77,14796,19122.25,23449.0,PA,Pennsylvania DC,83074.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
16,SKU0006,FL,Florida DC,0.85,23182,27406.75,31632.0,PA,Pennsylvania DC,160949.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
17,SKU0004,NV,Nevada DC,0.88,18297,20860.75,23425.0,PA,Pennsylvania DC,138719.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
18,SKU0018,FL,Florida DC,1.17,24731,21139.75,17549.0,PA,Pennsylvania DC,150698.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
19,SKU0017,WA,Washington DC,1.22,14071,11550.50,9030.0,None,None,NaN,Covered Risk,Monitor inbound supply / production
20,SKU0005,NV,Nevada DC,1.27,15118,11949.75,8782.0,None,None,NaN,Covered Risk,Monitor inbound supply / production
21,SKU0019,NV,Nevada DC,1.29,19659,15193.75,10729.0,None,None,NaN,Covered Risk,Monitor inbound supply / production
22,SKU0019,FL,Florida DC,1.32,21270,16082.00,10894.0,None,None,NaN,Covered Risk,Monitor inbound supply / production
23,SKU0017,FL,Florida DC,1.77,23042,12985.25,2929.0,None,None,NaN,Covered Risk,Monitor inbound supply / production
24,SKU0013,FL,Florida DC,1.79,21323,11911.25,2500.0,None,None,NaN,Covered Risk,Monitor inbound supply / production
25,SKU0013,NV,Nevada DC,1.83,21139,11537.00,1935.0,None,None,NaN,Covered Risk,Monitor inbound supply / production
26,SKU0019,WA,Washington DC,1.91,25955,13618.75,1283.0,None,None,NaN,Covered Risk,Monitor inbound supply / production

In [147]:
# 风险分布
con.sql("""
SELECT final_risk, COUNT(*) AS cnt
FROM risk_final
GROUP BY final_risk
ORDER BY cnt DESC
""").df()

                final_risk  cnt
0                  Healthy   46
1         True Supply Risk   14
2             Covered Risk    8
3  Rebalancing Opportunity    5

In [149]:
# Rebalancing cases
con.sql("""
SELECT *
FROM deployment_recommendation
WHERE final_risk = 'Rebalancing Opportunity'
ORDER BY shortage_wos ASC
""").df()

,sku_id,shortage_dc,shortage_dc_name,shortage_wos,unrestricted_inventory,avg_weekly_forecast,recommended_transfer_qty,donor_dc,donor_dc_name,donor_surplus_qty,final_risk,recommendation
0,SKU0020,NV,Nevada DC,0.44,9242,21205.75,33170.0,PA,Pennsylvania DC,123128.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
1,SKU0007,NV,Nevada DC,0.77,14796,19122.25,23449.0,PA,Pennsylvania DC,83074.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
2,SKU0006,FL,Florida DC,0.85,23182,27406.75,31632.0,PA,Pennsylvania DC,160949.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
3,SKU0004,NV,Nevada DC,0.88,18297,20860.75,23425.0,PA,Pennsylvania DC,138719.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC
4,SKU0018,FL,Florida DC,1.17,24731,21139.75,17549.0,PA,Pennsylvania DC,150698.0,Rebalancing Opportunity,Transfer inventory from donor DC to shortage DC

In [151]:
# True supply risk
con.sql("""
SELECT *
FROM deployment_recommendation
WHERE final_risk = 'True Supply Risk'
ORDER BY shortage_wos ASC
""").df()

,sku_id,shortage_dc,shortage_dc_name,shortage_wos,unrestricted_inventory,avg_weekly_forecast,recommended_transfer_qty,donor_dc,donor_dc_name,donor_surplus_qty,final_risk,recommendation
0,SKU0009,NV,Nevada DC,0.28,7208,25364.75,43522.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
1,SKU0014,FL,Florida DC,0.66,19985,30231.00,40477.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
2,SKU0008,WA,Washington DC,0.69,16022,23252.25,30483.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
3,SKU0012,NV,Nevada DC,0.76,17549,23157.25,28766.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
4,SKU0012,TX,Texas DC,1.06,19225,18209.75,17195.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
5,SKU0005,FL,Florida DC,1.13,14651,12994.25,11338.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
6,SKU0008,TX,Texas DC,1.13,23165,20416.50,17668.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
7,SKU0014,WA,Washington DC,1.17,21891,18708.25,15526.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
8,SKU0014,TX,Texas DC,1.38,31658,22905.50,14153.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
9,SKU0005,WA,Washington DC,1.40,15799,11245.50,6692.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
10,SKU0009,TX,Texas DC,1.52,30473,20042.00,9611.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
11,SKU0008,FL,Florida DC,1.80,35460,19680.25,3901.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
12,SKU0012,FL,Florida DC,1.84,31980,17402.25,2825.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...
13,SKU0009,FL,Florida DC,1.96,38461,19657.75,855.0,None,None,NaN,True Supply Risk,Escalate to planner: no feasible donor within ...

In [197]:
# Phase 5 — Time-Phased Inventory Projection & Replenishment Feasibility
# 这一步要做什么

# 对每个 sku_id + dc_id，按周滚动：
# Beginning Inventory
# + STO arriving this week
# + Production support arriving this week
# - Forecast this week
# = Projected Ending Inventory

# 然后判断：第几周开始出现 gap， gap 持续几周， STO 能不能在 gap 前补上， Production 能不能在 gap 前补上 是否需要 inter-DC transfer，是否完全无解

# 第 1 步：先把 SQL 结果拉进 pandas
# 先在 notebook 里运行下面这几段，把需要的表读出来。
# forecast by week
forecast_df = con.sql("""
SELECT
    sku_id,
    dc_id,
    dc_name,
    customer,
    forecast_week,
    forecast_qty
FROM forecast_4w
""").df()

forecast_df.head()

    sku_id dc_id          dc_name customer forecast_week  forecast_qty
0  SKU0001    NV        Nevada DC  Walmart      2026-W15          6023
1  SKU0001    PA  Pennsylvania DC  Walmart      2026-W15          7041
2  SKU0001    TX         Texas DC  Walmart      2026-W15          6237
3  SKU0002    PA  Pennsylvania DC  Walmart      2026-W15         11289
4  SKU0002    TX         Texas DC  Walmart      2026-W15         10423

In [157]:
# 第 2 步：准备辅助映射 我们需要把日期映射到 planning week。
weeks = ["2026-W15", "2026-W16", "2026-W17", "2026-W18"]

week_date_map = {
    "2026-W15": ("2026-04-07", "2026-04-13"),
    "2026-W16": ("2026-04-14", "2026-04-20"),
    "2026-W17": ("2026-04-21", "2026-04-27"),
    "2026-W18": ("2026-04-28", "2026-05-04"),
}

def date_to_week(date_val):
    if pd.isna(date_val):
        return None
    dt = pd.to_datetime(date_val)
    for wk, (start, end) in week_date_map.items():
        if pd.to_datetime(start) <= dt <= pd.to_datetime(end):
            return wk
    return None

In [199]:
# current inventory
inventory_df = con.sql("""
SELECT
    sku_id,
    dc_id,
    dc_name,
    unrestricted_inventory
FROM inventory_wos
""").df()

inventory_df.head()

    sku_id dc_id          dc_name  unrestricted_inventory
0  SKU0001    PA  Pennsylvania DC                   20949
1  SKU0001    TX         Texas DC                   31028
2  SKU0001    NV        Nevada DC                   15875
3  SKU0002    PA  Pennsylvania DC                   91533
4  SKU0002    TX         Texas DC                   75090

In [201]:
# low-WOS scope
risk_scope_df = con.sql("""
SELECT
    sku_id,
    dc_id,
    dc_name,
    wos
FROM inventory_wos
WHERE wos < 3
""").df()

risk_scope_df.head()

    sku_id dc_id        dc_name   wos
0  SKU0001    NV      Nevada DC  2.73
1  SKU0004    NV      Nevada DC  0.88
2  SKU0005    FL     Florida DC  1.13
3  SKU0005    NV      Nevada DC  1.27
4  SKU0005    WA  Washington DC  1.40

In [203]:
# donor candidates
donor_df = con.sql("""
SELECT
    sku_id,
    donor_dc,
    donor_dc_name,
    donor_surplus_qty,
    wos
FROM donor_candidates
""").df()

donor_df.head()

    sku_id donor_dc    donor_dc_name  donor_surplus_qty    wos
0  SKU0002       PA  Pennsylvania DC            68771.0   8.04
1  SKU0002       TX         Texas DC            53563.0   6.98
2  SKU0003       PA  Pennsylvania DC            63481.0   7.60
3  SKU0003       TX         Texas DC            73035.0   8.59
4  SKU0004       PA  Pennsylvania DC           138719.0  11.20

In [205]:
# STO inbound by week
sto_df = con.sql("""
SELECT
    sku_id,
    from_node,
    to_node,
    shipment_qty,
    pgi_date,
    pgr_date,
    should_deliver_date
FROM sto
""").df()

sto_df.head()

,sku_id,from_node,to_node,shipment_qty,pgi_date,pgr_date,should_deliver_date
0,SKU0019,PA,WA,39213,2026-04-12,None,2026-04-14
1,SKU0018,TX,FL,8733,2026-04-09,None,2026-04-15
2,SKU0013,PA,NV,43909,2026-04-09,None,2026-04-14
3,SKU0017,PA,WA,24679,2026-04-12,None,2026-04-13
4,SKU0005,PA,NV,44867,2026-04-10,None,2026-04-16

In [207]:
# production plan
prod_df = con.sql("""
SELECT
    sku_id,
    plant_id,
    plant_state,
    production_week,
    planned_qty
FROM production_frozen_4w
""").df()

prod_df.head()

    sku_id   plant_id plant_state production_week  planned_qty
0  SKU0001  Henderson          NV        2026-W15        33845
1  SKU0002        LHV          PA        2026-W15        57238
2  SKU0003        LHV          PA        2026-W15        86501
3  SKU0004  Henderson          NV        2026-W15        33557
4  SKU0005  Henderson          NV        2026-W15        28174

In [209]:
# transport lane
try:
    lane_df = con.sql("""
    SELECT
        from_node,
        to_node,
        mode,
        transit_days,
        transit_weeks,
        cost_per_case
    FROM transport_lane
    """).df()
except:
    lane_df = None
    print("transport_lane not loaded yet, will use simplified timing assumptions.")

transport_lane not loaded yet, will use simplified timing assumptions.

In [211]:
# 定义 projection scope
# 我们需要的不只是 low-WOS row，还要它们对应 SKU 的 donor rows。
projection_skus = sorted(risk_scope_df["sku_id"].unique().tolist())

projection_inventory_df = inventory_df[inventory_df["sku_id"].isin(projection_skus)].copy()
projection_forecast_df = forecast_df[forecast_df["sku_id"].isin(projection_skus)].copy()
projection_donor_df = donor_df[donor_df["sku_id"].isin(projection_skus)].copy()
projection_sto_df = sto_df[sto_df["sku_id"].isin(projection_skus)].copy()
projection_prod_df = prod_df[prod_df["sku_id"].isin(projection_skus)].copy()

print("projection_skus:", len(projection_skus))

projection_skus: 14

In [215]:
# 第 3 步：定义时间映射
# 我们现在只看：
# 2026-W15 2026-W16 2026-W17 2026-W18
# 先定义一个简单的 date → week bucket 函数
import pandas as pd
import numpy as np

projection_weeks = ["2026-W15", "2026-W16", "2026-W17", "2026-W18"]

week_date_map = {
    "2026-W15": ("2026-04-06", "2026-04-12"),
    "2026-W16": ("2026-04-13", "2026-04-19"),
    "2026-W17": ("2026-04-20", "2026-04-26"),
    "2026-W18": ("2026-04-27", "2026-05-03"),
}

def map_date_to_week(date_val):
    if pd.isna(date_val):
        return None
    d = pd.to_datetime(date_val)
    for wk, (start_date, end_date) in week_date_map.items():
        if pd.Timestamp(start_date) <= d <= pd.Timestamp(end_date):
            return wk
    return None

In [217]:
# 准备 weekly STO arrivals
projection_sto_df = projection_sto_df.copy()
projection_sto_df["arrival_week"] = projection_sto_df["should_deliver_date"].apply(map_date_to_week)

sto_weekly = (
    projection_sto_df[
        projection_sto_df["arrival_week"].isin(projection_weeks)
    ]
    .groupby(["sku_id", "to_node", "arrival_week"], as_index=False)
    .agg(inbound_sto_qty=("shipment_qty", "sum"))
    .rename(columns={"to_node": "dc_id"})
)

sto_weekly.head()

    sku_id dc_id arrival_week  inbound_sto_qty
0  SKU0005    NV     2026-W16            44867
1  SKU0013    NV     2026-W16            43909
2  SKU0017    WA     2026-W16            24679
3  SKU0018    FL     2026-W16             8733
4  SKU0019    WA     2026-W16            39213

In [219]:
# 准备 weekly production support
# 这里我们先用一个简化但合理的规则：
# 简化规则： production_week 本身就是可用周， 仅把生产量的 15% 视为某 DC 可分配支持， 本州 DC 优先能拿到， 也就是说，先只把 production support 给 plant_state 对应的 DC

# LHV → PA
# Henderson → NV
# Sulphur → TX
projection_prod_df = projection_prod_df.copy()
projection_prod_df["dc_id"] = projection_prod_df["plant_state"]
projection_prod_df["inbound_production_qty"] = (projection_prod_df["planned_qty"] * 0.15).round(0)

prod_weekly = (
    projection_prod_df.groupby(["sku_id", "dc_id", "production_week"], as_index=False)
    .agg(inbound_production_qty=("inbound_production_qty", "sum"))
    .rename(columns={"production_week": "week"})
)

prod_weekly.head()

    sku_id dc_id      week  inbound_production_qty
0  SKU0001    NV  2026-W15                  5077.0
1  SKU0001    NV  2026-W17                  5007.0
2  SKU0004    NV  2026-W15                  5034.0
3  SKU0004    NV  2026-W17                  3793.0
4  SKU0005    NV  2026-W15                  4226.0

In [221]:
# 准备 beginning inventory base
begin_inv_df = projection_inventory_df.copy()
begin_inv_df = begin_inv_df.rename(columns={"unrestricted_inventory": "begin_inventory"})
begin_inv_df.head()

     sku_id dc_id          dc_name  begin_inventory
0   SKU0001    PA  Pennsylvania DC            20949
1   SKU0001    TX         Texas DC            31028
2   SKU0001    NV        Nevada DC            15875
11  SKU0004    PA  Pennsylvania DC           168879
12  SKU0004    TX         Texas DC            73420

In [223]:
# 建立 rolling projection 主循环

weekly_projection_rows = []

# 建索引方便取数
forecast_lookup = {
    (row["sku_id"], row["dc_id"], row["forecast_week"]): row["forecast_qty"]
    for _, row in projection_forecast_df.iterrows()
}

sto_lookup = {
    (row["sku_id"], row["dc_id"], row["arrival_week"]): row["inbound_sto_qty"]
    for _, row in sto_weekly.iterrows()
}

prod_lookup = {
    (row["sku_id"], row["dc_id"], row["week"]): row["inbound_production_qty"]
    for _, row in prod_weekly.iterrows()
}

for _, base_row in begin_inv_df.iterrows():
    sku_id = base_row["sku_id"]
    dc_id = base_row["dc_id"]
    dc_name = base_row["dc_name"]
    beginning_inventory = base_row["begin_inventory"]

    current_inventory = beginning_inventory

    for week in projection_weeks:
        forecast_qty = forecast_lookup.get((sku_id, dc_id, week), 0)
        inbound_sto_qty = sto_lookup.get((sku_id, dc_id, week), 0)
        inbound_production_qty = prod_lookup.get((sku_id, dc_id, week), 0)

        projected_ending_inventory = (
            current_inventory
            + inbound_sto_qty
            + inbound_production_qty
            - forecast_qty
        )

        projected_wos = (
            projected_ending_inventory / forecast_qty
            if forecast_qty > 0 else None
        )

        gap_flag = 1 if projected_ending_inventory < 0 else 0

        weekly_projection_rows.append({
            "sku_id": sku_id,
            "dc_id": dc_id,
            "dc_name": dc_name,
            "week": week,
            "beginning_inventory": current_inventory,
            "forecast_qty": forecast_qty,
            "inbound_sto_qty": inbound_sto_qty,
            "inbound_production_qty": inbound_production_qty,
            "projected_ending_inventory": projected_ending_inventory,
            "projected_wos": round(projected_wos, 2) if projected_wos is not None else None,
            "gap_flag": gap_flag
        })

        current_inventory = projected_ending_inventory

weekly_inventory_projection = pd.DataFrame(weekly_projection_rows)
weekly_inventory_projection.head(20)

,sku_id,dc_id,dc_name,week,beginning_inventory,forecast_qty,inbound_sto_qty,inbound_production_qty,projected_ending_inventory,projected_wos,gap_flag
0,SKU0001,PA,Pennsylvania DC,2026-W15,20949.0,7041,0,0.0,13908.0,1.98,0
1,SKU0001,PA,Pennsylvania DC,2026-W16,13908.0,7283,0,0.0,6625.0,0.91,0
2,SKU0001,PA,Pennsylvania DC,2026-W17,6625.0,6282,0,0.0,343.0,0.05,0
3,SKU0001,PA,Pennsylvania DC,2026-W18,343.0,7039,0,0.0,-6696.0,-0.95,1
4,SKU0001,TX,Texas DC,2026-W15,31028.0,6237,0,0.0,24791.0,3.97,0
5,SKU0001,TX,Texas DC,2026-W16,24791.0,6246,0,0.0,18545.0,2.97,0
6,SKU0001,TX,Texas DC,2026-W17,18545.0,6045,0,0.0,12500.0,2.07,0
7,SKU0001,TX,Texas DC,2026-W18,12500.0,6131,0,0.0,6369.0,1.04,0
8,SKU0001,NV,Nevada DC,2026-W15,15875.0,6023,0,5077.0,14929.0,2.48,0
9,SKU0001,NV,Nevada DC,2026-W16,14929.0,5978,0,0.0,8951.0,1.50,0
10,SKU0001,NV,Nevada DC,2026-W17,8951.0,5613,0,5007.0,8345.0,1.49,0
11,SKU0001,NV,Nevada DC,2026-W18,8345.0,5629,0,0.0,2716.0,0.48,0
12,SKU0004,PA,Pennsylvania DC,2026-W15,168879.0,15547,0,0.0,153332.0,9.86,0
13,SKU0004,PA,Pennsylvania DC,2026-W16,153332.0,15541,0,0.0,137791.0,8.87,0
14,SKU0004,PA,Pennsylvania DC,2026-W17,137791.0,14757,0,0.0,123034.0,8.34,0
15,SKU0004,PA,Pennsylvania DC,2026-W18,123034.0,14476,0,0.0,108558.0,7.50,0
16,SKU0004,TX,Texas DC,2026-W15,73420.0,17780,0,0.0,55640.0,3.13,0
17,SKU0004,TX,Texas DC,2026-W16,55640.0,17011,0,0.0,38629.0,2.27,0
18,SKU0004,TX,Texas DC,2026-W17,38629.0,16263,0,0.0,22366.0,1.38,0
19,SKU0004,TX,Texas DC,2026-W18,22366.0,16448,0,0.0,5918.0,0.36,0

In [227]:
# 检查 projection 是否合理
weekly_inventory_projection.shape

(212, 11)

In [229]:
weekly_inventory_projection.sort_values(
    ["sku_id", "dc_id", "week"]
).head(30)

,sku_id,dc_id,dc_name,week,beginning_inventory,forecast_qty,inbound_sto_qty,inbound_production_qty,projected_ending_inventory,projected_wos,gap_flag
8,SKU0001,NV,Nevada DC,2026-W15,15875.0,6023,0,5077.0,14929.0,2.48,0
9,SKU0001,NV,Nevada DC,2026-W16,14929.0,5978,0,0.0,8951.0,1.50,0
10,SKU0001,NV,Nevada DC,2026-W17,8951.0,5613,0,5007.0,8345.0,1.49,0
11,SKU0001,NV,Nevada DC,2026-W18,8345.0,5629,0,0.0,2716.0,0.48,0
0,SKU0001,PA,Pennsylvania DC,2026-W15,20949.0,7041,0,0.0,13908.0,1.98,0
1,SKU0001,PA,Pennsylvania DC,2026-W16,13908.0,7283,0,0.0,6625.0,0.91,0
2,SKU0001,PA,Pennsylvania DC,2026-W17,6625.0,6282,0,0.0,343.0,0.05,0
3,SKU0001,PA,Pennsylvania DC,2026-W18,343.0,7039,0,0.0,-6696.0,-0.95,1
4,SKU0001,TX,Texas DC,2026-W15,31028.0,6237,0,0.0,24791.0,3.97,0
5,SKU0001,TX,Texas DC,2026-W16,24791.0,6246,0,0.0,18545.0,2.97,0
6,SKU0001,TX,Texas DC,2026-W17,18545.0,6045,0,0.0,12500.0,2.07,0
7,SKU0001,TX,Texas DC,2026-W18,12500.0,6131,0,0.0,6369.0,1.04,0
20,SKU0004,NV,Nevada DC,2026-W15,18297.0,21691,0,5034.0,1640.0,0.08,0
21,SKU0004,NV,Nevada DC,2026-W16,1640.0,20210,0,0.0,-18570.0,-0.92,1
22,SKU0004,NV,Nevada DC,2026-W17,-18570.0,20940,0,3793.0,-35717.0,-1.71,1
23,SKU0004,NV,Nevada DC,2026-W18,-35717.0,20602,0,0.0,-56319.0,-2.73,1
12,SKU0004,PA,Pennsylvania DC,2026-W15,168879.0,15547,0,0.0,153332.0,9.86,0
13,SKU0004,PA,Pennsylvania DC,2026-W16,153332.0,15541,0,0.0,137791.0,8.87,0
14,SKU0004,PA,Pennsylvania DC,2026-W17,137791.0,14757,0,0.0,123034.0,8.34,0
15,SKU0004,PA,Pennsylvania DC,2026-W18,123034.0,14476,0,0.0,108558.0,7.50,0
16,SKU0004,TX,Texas DC,2026-W15,73420.0,17780,0,0.0,55640.0,3.13,0
17,SKU0004,TX,Texas DC,2026-W16,55640.0,17011,0,0.0,38629.0,2.27,0
18,SKU0004,TX,Texas DC,2026-W17,38629.0,16263,0,0.0,22366.0,1.38,0
19,SKU0004,TX,Texas DC,2026-W18,22366.0,16448,0,0.0,5918.0,0.36,0
24,SKU0004,WI,Wisconsin DC,2026-W15,58061.0,15395,0,0.0,42666.0,2.77,0
25,SKU0004,WI,Wisconsin DC,2026-W16,42666.0,14235,0,0.0,28431.0,2.00,0
26,SKU0004,WI,Wisconsin DC,2026-W17,28431.0,14365,0,0.0,14066.0,0.98,0
27,SKU0004,WI,Wisconsin DC,2026-W18,14066.0,16049,0,0.0,-1983.0,-0.12,1
32,SKU0005,FL,Florida DC,2026-W15,14651.0,12618,0,0.0,2033.0,0.16,0
33,SKU0005,FL,Florida DC,2026-W16,2033.0,13384,0,0.0,-11351.0,-0.85,1

In [231]:
weekly_inventory_projection[
    weekly_inventory_projection["gap_flag"] == 1
].sort_values(["sku_id", "dc_id", "week"]).head(30)

,sku_id,dc_id,dc_name,week,beginning_inventory,forecast_qty,inbound_sto_qty,inbound_production_qty,projected_ending_inventory,projected_wos,gap_flag
3,SKU0001,PA,Pennsylvania DC,2026-W18,343.0,7039,0,0.0,-6696.0,-0.95,1
21,SKU0004,NV,Nevada DC,2026-W16,1640.0,20210,0,0.0,-18570.0,-0.92,1
22,SKU0004,NV,Nevada DC,2026-W17,-18570.0,20940,0,3793.0,-35717.0,-1.71,1
23,SKU0004,NV,Nevada DC,2026-W18,-35717.0,20602,0,0.0,-56319.0,-2.73,1
27,SKU0004,WI,Wisconsin DC,2026-W18,14066.0,16049,0,0.0,-1983.0,-0.12,1
33,SKU0005,FL,Florida DC,2026-W16,2033.0,13384,0,0.0,-11351.0,-0.85,1
34,SKU0005,FL,Florida DC,2026-W17,-11351.0,12427,0,0.0,-23778.0,-1.91,1
35,SKU0005,FL,Florida DC,2026-W18,-23778.0,13548,0,0.0,-37326.0,-2.76,1
31,SKU0005,PA,Pennsylvania DC,2026-W18,1093.0,14085,0,0.0,-12992.0,-0.92,1
41,SKU0005,WA,Washington DC,2026-W16,4250.0,10784,0,0.0,-6534.0,-0.61,1
42,SKU0005,WA,Washington DC,2026-W17,-6534.0,11345,0,0.0,-17879.0,-1.58,1
43,SKU0005,WA,Washington DC,2026-W18,-17879.0,11304,0,0.0,-29183.0,-2.58,1
52,SKU0006,FL,Florida DC,2026-W15,23182.0,26252,0,0.0,-3070.0,-0.12,1
53,SKU0006,FL,Florida DC,2026-W16,-3070.0,27377,0,0.0,-30447.0,-1.11,1
54,SKU0006,FL,Florida DC,2026-W17,-30447.0,28508,0,0.0,-58955.0,-2.07,1
55,SKU0006,FL,Florida DC,2026-W18,-58955.0,27490,0,0.0,-86445.0,-3.14,1
51,SKU0006,TX,Texas DC,2026-W18,12961.0,22935,0,0.0,-9974.0,-0.43,1
59,SKU0006,WI,Wisconsin DC,2026-W18,9163.0,19231,0,0.0,-10068.0,-0.52,1
68,SKU0007,NV,Nevada DC,2026-W15,14796.0,19163,0,0.0,-4367.0,-0.23,1
69,SKU0007,NV,Nevada DC,2026-W16,-4367.0,18546,0,3658.0,-19255.0,-1.04,1
70,SKU0007,NV,Nevada DC,2026-W17,-19255.0,19737,0,0.0,-38992.0,-1.98,1
71,SKU0007,NV,Nevada DC,2026-W18,-38992.0,19043,0,0.0,-58035.0,-3.05,1
67,SKU0007,TX,Texas DC,2026-W18,11589.0,16012,0,0.0,-4423.0,-0.28,1
75,SKU0007,WI,Wisconsin DC,2026-W18,7132.0,13040,0,0.0,-5908.0,-0.45,1
81,SKU0008,FL,Florida DC,2026-W16,16724.0,19534,0,0.0,-2810.0,-0.14,1
82,SKU0008,FL,Florida DC,2026-W17,-2810.0,19427,0,0.0,-22237.0,-1.14,1
83,SKU0008,FL,Florida DC,2026-W18,-22237.0,21024,0,0.0,-43261.0,-2.06,1
77,SKU0008,TX,Texas DC,2026-W16,2017.0,20823,0,0.0,-18806.0,-0.90,1
78,SKU0008,TX,Texas DC,2026-W17,-18806.0,19061,0,0.0,-37867.0,-1.99,1
79,SKU0008,TX,Texas DC,2026-W18,-37867.0,20634,0,0.0,-58501.0,-2.84,1

In [233]:
# 做 gap summary
gap_only = weekly_inventory_projection[
    weekly_inventory_projection["gap_flag"] == 1
].copy()

if len(gap_only) > 0:
    gap_summary = (
        gap_only.groupby(["sku_id", "dc_id", "dc_name"], as_index=False)
        .agg(
            first_gap_week=("week", "min"),
            total_gap_weeks=("week", "count"),
            max_gap_qty=("projected_ending_inventory", "min"),
            cumulative_gap_qty=("projected_ending_inventory", "sum")
        )
    )
else:
    gap_summary = pd.DataFrame(columns=[
        "sku_id", "dc_id", "dc_name",
        "first_gap_week", "total_gap_weeks",
        "max_gap_qty", "cumulative_gap_qty"
    ])

gap_summary.head()

,sku_id,dc_id,dc_name,first_gap_week,total_gap_weeks,max_gap_qty,cumulative_gap_qty
0,SKU0001,PA,Pennsylvania DC,2026-W18,1,-6696.0,-6696.0
1,SKU0004,NV,Nevada DC,2026-W16,3,-56319.0,-110606.0
2,SKU0004,WI,Wisconsin DC,2026-W18,1,-1983.0,-1983.0
3,SKU0005,FL,Florida DC,2026-W16,3,-37326.0,-72455.0
4,SKU0005,PA,Pennsylvania DC,2026-W18,1,-12992.0,-12992.0

In [235]:
# 做 replenishment feasibility

# 这里先做第一版可行性判断：对于每个 gap case：是否已有 STO 在 first gap week 前到达； 是否已有 production support 在 first gap week 前到达； 是否存在 donor DC； 最佳 donor 是谁

#  donor best source：
best_donor_df = (
    projection_donor_df.sort_values(["sku_id", "wos", "donor_surplus_qty"], ascending=[True, False, False])
    .drop_duplicates(subset=["sku_id"])
    .copy()
)

best_donor_df.head()

     sku_id donor_dc    donor_dc_name  donor_surplus_qty    wos
4   SKU0004       PA  Pennsylvania DC           138719.0  11.20
5   SKU0006       PA  Pennsylvania DC           160949.0  10.41
6   SKU0007       PA  Pennsylvania DC            83074.0   8.19
11  SKU0018       PA  Pennsylvania DC           150698.0  12.23
12  SKU0020       PA  Pennsylvania DC           123128.0  10.29

In [257]:
# =========================
# Final replenishment_feasibility
# =========================

# 1) 先选每个 SKU 的最佳 donor
best_donor_df = (
    projection_donor_df
    .sort_values(
        ["sku_id", "wos", "donor_surplus_qty"],
        ascending=[True, False, False]
    )
    .drop_duplicates(subset=["sku_id"])
    .copy()
)

week_order = {wk: i for i, wk in enumerate(projection_weeks)}

replenishment_rows = []

for _, gap_row in gap_summary.iterrows():
    sku_id = gap_row["sku_id"]
    shortage_dc = gap_row["dc_id"]
    shortage_dc_name = gap_row["dc_name"]
    first_gap_week = gap_row["first_gap_week"]
    gap_idx = week_order[first_gap_week]

    max_gap_qty_abs = abs(gap_row["max_gap_qty"])
    cumulative_gap_qty_abs = abs(gap_row["cumulative_gap_qty"])
    total_gap_weeks = gap_row["total_gap_weeks"]

    # ---- support arriving on or before first gap week ----
    sto_qty = sto_weekly[
        (sto_weekly["sku_id"] == sku_id) &
        (sto_weekly["dc_id"] == shortage_dc) &
        (sto_weekly["arrival_week"].map(week_order) <= gap_idx)
    ]["inbound_sto_qty"].sum()

    prod_qty = prod_weekly[
        (prod_weekly["sku_id"] == sku_id) &
        (prod_weekly["dc_id"] == shortage_dc) &
        (prod_weekly["week"].map(week_order) <= gap_idx)
    ]["inbound_production_qty"].sum()

    donor_match = best_donor_df[best_donor_df["sku_id"] == sku_id]

    donor_exists = 1 if len(donor_match) > 0 else 0

    if donor_exists:
        best_donor_dc = donor_match.iloc[0]["donor_dc"]
        best_donor_dc_name = donor_match.iloc[0]["donor_dc_name"]
        donor_surplus_qty = float(donor_match.iloc[0]["donor_surplus_qty"])
        donor_wos = float(donor_match.iloc[0]["wos"])
    else:
        best_donor_dc = None
        best_donor_dc_name = None
        donor_surplus_qty = 0.0
        donor_wos = None

    # ---- quantity targets ----
    # minimum qty to stop the first severe stockout
    qty_to_stabilize = max_gap_qty_abs

    # qty to fully cover cumulative gap across all gap weeks
    qty_to_full_cover = cumulative_gap_qty_abs

    # average weekly gap can be useful as a softer threshold
    avg_gap_per_gap_week = cumulative_gap_qty_abs / total_gap_weeks if total_gap_weeks > 0 else 0

    # ---- stronger coverage logic ----
    # strict cover = can stabilize first gap
    sto_covers_first_gap = sto_qty >= qty_to_stabilize
    prod_covers_first_gap = prod_qty >= qty_to_stabilize

    # softer cover = at least meaningfully offsets the shortage
    sto_partially_covers = sto_qty >= 0.5 * qty_to_stabilize
    prod_partially_covers = prod_qty >= 0.5 * qty_to_stabilize

    donor_can_stabilize = donor_exists and donor_surplus_qty >= qty_to_stabilize
    donor_can_partially_cover = donor_exists and donor_surplus_qty >= avg_gap_per_gap_week

    # ---- decision logic ----
    if sto_covers_first_gap:
        feasible_action_type = "Covered by STO"
        recommended_source = "In-transit STO"
        recommended_qty = None
        business_reason = "Inbound STO arriving by or before the first gap week is sufficient to cover the initial shortage."

    elif prod_covers_first_gap:
        feasible_action_type = "Covered by Production"
        recommended_source = "Primary plant production"
        recommended_qty = None
        business_reason = "Frozen-horizon production support is sufficient to stabilize the first shortage week."

    elif donor_can_stabilize:
        feasible_action_type = "Transfer Required"
        recommended_source = best_donor_dc
        recommended_qty = min(qty_to_full_cover, donor_surplus_qty)
        business_reason = "No timely STO or sufficient production support; donor DC has enough surplus inventory to cover the shortage."

    elif sto_partially_covers or prod_partially_covers or donor_can_partially_cover:
        feasible_action_type = "Partial Transfer / Escalate"

        if donor_exists:
            recommended_source = best_donor_dc
            recommended_qty = min(qty_to_stabilize, donor_surplus_qty)
            business_reason = "Available support can partially mitigate the shortage, but not fully cover the projected gap."
        else:
            recommended_source = None
            recommended_qty = None
            business_reason = "Some supply support exists, but it is insufficient to stabilize the shortage without planner intervention."

    else:
        feasible_action_type = "No Feasible Source"
        recommended_source = None
        recommended_qty = None
        business_reason = "No timely STO, insufficient production support, and no donor DC with enough surplus inventory."

    replenishment_rows.append({
        "sku_id": sku_id,
        "shortage_dc": shortage_dc,
        "shortage_dc_name": shortage_dc_name,
        "first_gap_week": first_gap_week,
        "total_gap_weeks": total_gap_weeks,
        "max_gap_qty_abs": max_gap_qty_abs,
        "cumulative_gap_qty_abs": cumulative_gap_qty_abs,
        "qty_to_stabilize": qty_to_stabilize,
        "qty_to_full_cover": qty_to_full_cover,
        "avg_gap_per_gap_week": avg_gap_per_gap_week,
        "sto_can_cover_qty": sto_qty,
        "production_can_cover_qty": prod_qty,
        "donor_exists": donor_exists,
        "best_donor_dc": best_donor_dc,
        "best_donor_dc_name": best_donor_dc_name,
        "donor_surplus_qty": donor_surplus_qty,
        "donor_wos": donor_wos,
        "recommended_source": recommended_source,
        "feasible_action_type": feasible_action_type,
        "business_reason": business_reason
    })

replenishment_feasibility = pd.DataFrame(replenishment_rows)
replenishment_feasibility.head(20)

,sku_id,shortage_dc,shortage_dc_name,first_gap_week,total_gap_weeks,max_gap_qty_abs,cumulative_gap_qty_abs,qty_to_stabilize,qty_to_full_cover,avg_gap_per_gap_week,sto_can_cover_qty,production_can_cover_qty,donor_exists,best_donor_dc,best_donor_dc_name,donor_surplus_qty,donor_wos,recommended_source,feasible_action_type,business_reason
0,SKU0001,PA,Pennsylvania DC,2026-W18,1,6696.0,6696.0,6696.0,6696.0,6696.000000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
1,SKU0004,NV,Nevada DC,2026-W16,3,56319.0,110606.0,56319.0,110606.0,36868.666667,0,5034.0,1,PA,Pennsylvania DC,138719.0,11.20,PA,Transfer Required,No timely STO or sufficient production support...
2,SKU0004,WI,Wisconsin DC,2026-W18,1,1983.0,1983.0,1983.0,1983.0,1983.000000,0,0.0,1,PA,Pennsylvania DC,138719.0,11.20,PA,Transfer Required,No timely STO or sufficient production support...
3,SKU0005,FL,Florida DC,2026-W16,3,37326.0,72455.0,37326.0,72455.0,24151.666667,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
4,SKU0005,PA,Pennsylvania DC,2026-W18,1,12992.0,12992.0,12992.0,12992.0,12992.000000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
5,SKU0005,WA,Washington DC,2026-W16,3,29183.0,53596.0,29183.0,53596.0,17865.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
6,SKU0006,FL,Florida DC,2026-W15,4,86445.0,178917.0,86445.0,178917.0,44729.250000,0,0.0,1,PA,Pennsylvania DC,160949.0,10.41,PA,Transfer Required,No timely STO or sufficient production support...
7,SKU0006,TX,Texas DC,2026-W18,1,9974.0,9974.0,9974.0,9974.0,9974.000000,0,2259.0,1,PA,Pennsylvania DC,160949.0,10.41,PA,Transfer Required,No timely STO or sufficient production support...
8,SKU0006,WI,Wisconsin DC,2026-W18,1,10068.0,10068.0,10068.0,10068.0,10068.000000,0,0.0,1,PA,Pennsylvania DC,160949.0,10.41,PA,Transfer Required,No timely STO or sufficient production support...
9,SKU0007,NV,Nevada DC,2026-W15,4,58035.0,120649.0,58035.0,120649.0,30162.250000,0,0.0,1,PA,Pennsylvania DC,83074.0,8.19,PA,Transfer Required,No timely STO or sufficient production support...
10,SKU0007,TX,Texas DC,2026-W18,1,4423.0,4423.0,4423.0,4423.0,4423.000000,0,0.0,1,PA,Pennsylvania DC,83074.0,8.19,PA,Transfer Required,No timely STO or sufficient production support...
11,SKU0007,WI,Wisconsin DC,2026-W18,1,5908.0,5908.0,5908.0,5908.0,5908.000000,0,0.0,1,PA,Pennsylvania DC,83074.0,8.19,PA,Transfer Required,No timely STO or sufficient production support...
12,SKU0008,FL,Florida DC,2026-W16,3,43261.0,68308.0,43261.0,68308.0,22769.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
13,SKU0008,TX,Texas DC,2026-W16,3,58501.0,115174.0,58501.0,115174.0,38391.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
14,SKU0008,WA,Washington DC,2026-W15,4,76987.0,173280.0,76987.0,173280.0,43320.000000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
15,SKU0009,FL,Florida DC,2026-W16,3,40170.0,65128.0,40170.0,65128.0,21709.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
16,SKU0009,NV,Nevada DC,2026-W15,4,94251.0,223670.0,94251.0,223670.0,55917.500000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
17,SKU0009,TX,Texas DC,2026-W16,3,49695.0,89830.0,49695.0,89830.0,29943.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
18,SKU0009,WA,Washington DC,2026-W17,2,31006.0,45638.0,31006.0,45638.0,22819.000000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
19,SKU0012,FL,Florida DC,2026-W16,3,37629.0,62026.0,37629.0,62026.0,20675.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."

In [259]:
# 注意： max_gap_qty 这里会是最负的库存值 （ 应该在gap summary 后面） 
# cumulative_gap_qty 也是负值累加
# 如果你想更直观，可以转成正的 gap magnitude：
if len(gap_summary) > 0:
    gap_summary["max_gap_qty_abs"] = gap_summary["max_gap_qty"].abs()
    gap_summary["cumulative_gap_qty_abs"] = gap_summary["cumulative_gap_qty"].abs()

In [261]:
# =========================
# Final recommendation
# =========================

final_recommendation = replenishment_feasibility.copy()

# 更清晰的 action text
action_map = {
    "Covered by STO": "Monitor inbound STO and hold deployment",
    "Covered by Production": "Monitor plant replenishment, no transfer needed",
    "Transfer Required": "Transfer inventory from donor DC to shortage DC",
    "Partial Transfer / Escalate": "Execute partial transfer and escalate remaining gap to planner",
    "No Feasible Source": "Escalate to planner: no timely supply or donor available"
}

final_recommendation["recommended_action"] = final_recommendation["feasible_action_type"].map(action_map)

# 两个 quantity 版本：先救火 vs 尽量补平
def calc_recommended_qty_stabilize(row):
    if row["feasible_action_type"] in ["Transfer Required", "Partial Transfer / Escalate"] and row["donor_exists"] == 1:
        return min(row["qty_to_stabilize"], row["donor_surplus_qty"])
    return None

def calc_recommended_qty_full_cover(row):
    if row["feasible_action_type"] == "Transfer Required" and row["donor_exists"] == 1:
        return min(row["qty_to_full_cover"], row["donor_surplus_qty"])
    elif row["feasible_action_type"] == "Partial Transfer / Escalate" and row["donor_exists"] == 1:
        return min(row["qty_to_stabilize"], row["donor_surplus_qty"])
    return None

final_recommendation["recommended_qty_stabilize"] = final_recommendation.apply(
    calc_recommended_qty_stabilize, axis=1
)

final_recommendation["recommended_qty_full_cover"] = final_recommendation.apply(
    calc_recommended_qty_full_cover, axis=1
)

# priority for sorting in BI / reporting
priority_map = {
    "No Feasible Source": 1,
    "Partial Transfer / Escalate": 2,
    "Transfer Required": 3,
    "Covered by Production": 4,
    "Covered by STO": 5
}
final_recommendation["action_priority"] = final_recommendation["feasible_action_type"].map(priority_map)

# 最终输出列
final_recommendation = final_recommendation[[
    "sku_id",
    "shortage_dc",
    "shortage_dc_name",
    "first_gap_week",
    "total_gap_weeks",
    "max_gap_qty_abs",
    "cumulative_gap_qty_abs",
    "qty_to_stabilize",
    "qty_to_full_cover",
    "avg_gap_per_gap_week",
    "sto_can_cover_qty",
    "production_can_cover_qty",
    "donor_exists",
    "best_donor_dc",
    "best_donor_dc_name",
    "donor_surplus_qty",
    "donor_wos",
    "feasible_action_type",
    "recommended_source",
    "recommended_action",
    "recommended_qty_stabilize",
    "recommended_qty_full_cover",
    "business_reason",
    "action_priority"
]].rename(columns={
    "shortage_dc": "dc_id",
    "shortage_dc_name": "dc_name"
})

final_recommendation = final_recommendation.sort_values(
    ["action_priority", "first_gap_week", "cumulative_gap_qty_abs"],
    ascending=[True, True, False]
).reset_index(drop=True)

final_recommendation.head(30)

,sku_id,dc_id,dc_name,first_gap_week,total_gap_weeks,max_gap_qty_abs,cumulative_gap_qty_abs,qty_to_stabilize,qty_to_full_cover,avg_gap_per_gap_week,...,best_donor_dc_name,donor_surplus_qty,donor_wos,feasible_action_type,recommended_source,recommended_action,recommended_qty_stabilize,recommended_qty_full_cover,business_reason,action_priority
0,SKU0014,FL,Florida DC,2026-W15,4,100939.0,224710.0,100939.0,224710.0,56177.500000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
1,SKU0009,NV,Nevada DC,2026-W15,4,94251.0,223670.0,94251.0,223670.0,55917.500000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
2,SKU0008,WA,Washington DC,2026-W15,4,76987.0,173280.0,76987.0,173280.0,43320.000000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
3,SKU0012,NV,Nevada DC,2026-W15,4,75080.0,162134.0,75080.0,162134.0,40533.500000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
4,SKU0008,TX,Texas DC,2026-W16,3,58501.0,115174.0,58501.0,115174.0,38391.333333,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
5,SKU0014,TX,Texas DC,2026-W16,3,59964.0,109418.0,59964.0,109418.0,36472.666667,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
6,SKU0012,TX,Texas DC,2026-W16,3,53614.0,106526.0,53614.0,106526.0,35508.666667,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
7,SKU0014,WA,Washington DC,2026-W16,3,52942.0,101726.0,52942.0,101726.0,33908.666667,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
8,SKU0009,TX,Texas DC,2026-W16,3,49695.0,89830.0,49695.0,89830.0,29943.333333,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
9,SKU0019,FL,Florida DC,2026-W16,3,43058.0,80933.0,43058.0,80933.0,26977.666667,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
10,SKU0005,FL,Florida DC,2026-W16,3,37326.0,72455.0,37326.0,72455.0,24151.666667,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
11,SKU0008,FL,Florida DC,2026-W16,3,43261.0,68308.0,43261.0,68308.0,22769.333333,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
12,SKU0009,FL,Florida DC,2026-W16,3,40170.0,65128.0,40170.0,65128.0,21709.333333,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
13,SKU0012,FL,Florida DC,2026-W16,3,37629.0,62026.0,37629.0,62026.0,20675.333333,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
14,SKU0005,WA,Washington DC,2026-W16,3,29183.0,53596.0,29183.0,53596.0,17865.333333,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
15,SKU0017,FL,Florida DC,2026-W16,3,28899.0,48122.0,28899.0,48122.0,16040.666667,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
16,SKU0013,FL,Florida DC,2026-W16,3,26322.0,43627.0,26322.0,43627.0,14542.333333,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
17,SKU0009,WA,Washington DC,2026-W17,2,31006.0,45638.0,31006.0,45638.0,22819.000000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
18,SKU0013,WA,Washington DC,2026-W17,2,21450.0,31830.0,21450.0,31830.0,15915.000000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
19,SKU0012,WA,Washington DC,2026-W17,2,21715.0,27766.0,21715.0,27766.0,13883.000000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
20,SKU0017,PA,Pennsylvania DC,2026-W17,2,13740.0,14504.0,13740.0,14504.0,7252.000000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
21,SKU0005,PA,Pennsylvania DC,2026-W18,1,12992.0,12992.0,12992.0,12992.0,12992.000000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
22,SKU0019,PA,Pennsylvania DC,2026-W18,1,12380.0,12380.0,12380.0,12380.0,12380.000000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
23,SKU0001,PA,Pennsylvania DC,2026-W18,1,6696.0,6696.0,6696.0,6696.0,6696.000000,...,None,0.0,NaN,No Feasible Source,None,Escalate to planner: no timely supply or donor...,NaN,NaN,"No timely STO, insufficient production support...",1
24,SKU0006,FL,Florida DC,2026-W15,4,86445.0,178917.0,86445.0,178917.0,44729.250000,...,Pennsylvania DC,160949.0,10.41,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,86445.0,160949.0,No timely STO or sufficient production support...,3
25,SKU0020,NV,Nevada DC,2026-W15,4,68529.0,159073.0,68529.0,159073.0,39768.250000,...,Pennsylvania DC,123128.0,10.29,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,68529.0,123128.0,No timely STO or sufficient production support...,3
26,SKU0007,NV,Nevada DC,2026-W15,4,58035.0,120649.0,58035.0,120649.0,30162.250000,...,Pennsylvania DC,83074.0,8.19,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,58035.0,83074.0,No timely STO or sufficient production support...,3
27,SKU0004,NV,Nevada DC,2026-W16,3,56319.0,110606.0,56319.0,110606.0,36868.666667,...,Pennsylvania DC,138719.0,11.20,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,56319.0,110606.0,No timely STO or sufficient production support...,3
28,SKU0018,FL,Florida DC,2026-W16,3,51095.0,86587.0,51095.0,86587.0,28862.333333,...,Pennsylvania DC,150698.0,12.23,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,51095.0,86587.0,No timely STO or sufficient production support...,3
29,SKU0020,WI,Wisconsin DC,2026-W18,1,11667.0,11667.0,11667.0,11667.0,11667.000000,...,Pennsylvania DC,123128.0,10.29,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,11667.0,11667.0,No timely STO or sufficient production support...,3

In [263]:
# ----- 重点看 4 个结果
# weekly projection
weekly_inventory_projection.head(30)

,sku_id,dc_id,dc_name,week,beginning_inventory,forecast_qty,inbound_sto_qty,inbound_production_qty,projected_ending_inventory,projected_wos,gap_flag
0,SKU0001,PA,Pennsylvania DC,2026-W15,20949.0,7041,0,0.0,13908.0,1.98,0
1,SKU0001,PA,Pennsylvania DC,2026-W16,13908.0,7283,0,0.0,6625.0,0.91,0
2,SKU0001,PA,Pennsylvania DC,2026-W17,6625.0,6282,0,0.0,343.0,0.05,0
3,SKU0001,PA,Pennsylvania DC,2026-W18,343.0,7039,0,0.0,-6696.0,-0.95,1
4,SKU0001,TX,Texas DC,2026-W15,31028.0,6237,0,0.0,24791.0,3.97,0
5,SKU0001,TX,Texas DC,2026-W16,24791.0,6246,0,0.0,18545.0,2.97,0
6,SKU0001,TX,Texas DC,2026-W17,18545.0,6045,0,0.0,12500.0,2.07,0
7,SKU0001,TX,Texas DC,2026-W18,12500.0,6131,0,0.0,6369.0,1.04,0
8,SKU0001,NV,Nevada DC,2026-W15,15875.0,6023,0,5077.0,14929.0,2.48,0
9,SKU0001,NV,Nevada DC,2026-W16,14929.0,5978,0,0.0,8951.0,1.50,0
10,SKU0001,NV,Nevada DC,2026-W17,8951.0,5613,0,5007.0,8345.0,1.49,0
11,SKU0001,NV,Nevada DC,2026-W18,8345.0,5629,0,0.0,2716.0,0.48,0
12,SKU0004,PA,Pennsylvania DC,2026-W15,168879.0,15547,0,0.0,153332.0,9.86,0
13,SKU0004,PA,Pennsylvania DC,2026-W16,153332.0,15541,0,0.0,137791.0,8.87,0
14,SKU0004,PA,Pennsylvania DC,2026-W17,137791.0,14757,0,0.0,123034.0,8.34,0
15,SKU0004,PA,Pennsylvania DC,2026-W18,123034.0,14476,0,0.0,108558.0,7.50,0
16,SKU0004,TX,Texas DC,2026-W15,73420.0,17780,0,0.0,55640.0,3.13,0
17,SKU0004,TX,Texas DC,2026-W16,55640.0,17011,0,0.0,38629.0,2.27,0
18,SKU0004,TX,Texas DC,2026-W17,38629.0,16263,0,0.0,22366.0,1.38,0
19,SKU0004,TX,Texas DC,2026-W18,22366.0,16448,0,0.0,5918.0,0.36,0
20,SKU0004,NV,Nevada DC,2026-W15,18297.0,21691,0,5034.0,1640.0,0.08,0
21,SKU0004,NV,Nevada DC,2026-W16,1640.0,20210,0,0.0,-18570.0,-0.92,1
22,SKU0004,NV,Nevada DC,2026-W17,-18570.0,20940,0,3793.0,-35717.0,-1.71,1
23,SKU0004,NV,Nevada DC,2026-W18,-35717.0,20602,0,0.0,-56319.0,-2.73,1
24,SKU0004,WI,Wisconsin DC,2026-W15,58061.0,15395,0,0.0,42666.0,2.77,0
25,SKU0004,WI,Wisconsin DC,2026-W16,42666.0,14235,0,0.0,28431.0,2.00,0
26,SKU0004,WI,Wisconsin DC,2026-W17,28431.0,14365,0,0.0,14066.0,0.98,0
27,SKU0004,WI,Wisconsin DC,2026-W18,14066.0,16049,0,0.0,-1983.0,-0.12,1
28,SKU0005,PA,Pennsylvania DC,2026-W15,43799.0,13952,0,0.0,29847.0,2.14,0
29,SKU0005,PA,Pennsylvania DC,2026-W16,29847.0,14099,0,0.0,15748.0,1.12,0

In [265]:
# gap summary
gap_summary.sort_values(["first_gap_week", "max_gap_qty_abs"], ascending=[True, False]).head(20)

,sku_id,dc_id,dc_name,first_gap_week,total_gap_weeks,max_gap_qty,cumulative_gap_qty,max_gap_qty_abs,cumulative_gap_qty_abs
25,SKU0014,FL,Florida DC,2026-W15,4,-100939.0,-224710.0,100939.0,224710.0
16,SKU0009,NV,Nevada DC,2026-W15,4,-94251.0,-223670.0,94251.0,223670.0
6,SKU0006,FL,Florida DC,2026-W15,4,-86445.0,-178917.0,86445.0,178917.0
14,SKU0008,WA,Washington DC,2026-W15,4,-76987.0,-173280.0,76987.0,173280.0
20,SKU0012,NV,Nevada DC,2026-W15,4,-75080.0,-162134.0,75080.0,162134.0
38,SKU0020,NV,Nevada DC,2026-W15,4,-68529.0,-159073.0,68529.0,159073.0
9,SKU0007,NV,Nevada DC,2026-W15,4,-58035.0,-120649.0,58035.0,120649.0
26,SKU0014,TX,Texas DC,2026-W16,3,-59964.0,-109418.0,59964.0,109418.0
13,SKU0008,TX,Texas DC,2026-W16,3,-58501.0,-115174.0,58501.0,115174.0
1,SKU0004,NV,Nevada DC,2026-W16,3,-56319.0,-110606.0,56319.0,110606.0
21,SKU0012,TX,Texas DC,2026-W16,3,-53614.0,-106526.0,53614.0,106526.0
27,SKU0014,WA,Washington DC,2026-W16,3,-52942.0,-101726.0,52942.0,101726.0
32,SKU0018,FL,Florida DC,2026-W16,3,-51095.0,-86587.0,51095.0,86587.0
17,SKU0009,TX,Texas DC,2026-W16,3,-49695.0,-89830.0,49695.0,89830.0
12,SKU0008,FL,Florida DC,2026-W16,3,-43261.0,-68308.0,43261.0,68308.0
35,SKU0019,FL,Florida DC,2026-W16,3,-43058.0,-80933.0,43058.0,80933.0
15,SKU0009,FL,Florida DC,2026-W16,3,-40170.0,-65128.0,40170.0,65128.0
19,SKU0012,FL,Florida DC,2026-W16,3,-37629.0,-62026.0,37629.0,62026.0
3,SKU0005,FL,Florida DC,2026-W16,3,-37326.0,-72455.0,37326.0,72455.0
5,SKU0005,WA,Washington DC,2026-W16,3,-29183.0,-53596.0,29183.0,53596.0

In [267]:
# replenishment_feasibility
replenishment_feasibility.sort_values("first_gap_week").head(20)

,sku_id,shortage_dc,shortage_dc_name,first_gap_week,total_gap_weeks,max_gap_qty_abs,cumulative_gap_qty_abs,qty_to_stabilize,qty_to_full_cover,avg_gap_per_gap_week,sto_can_cover_qty,production_can_cover_qty,donor_exists,best_donor_dc,best_donor_dc_name,donor_surplus_qty,donor_wos,recommended_source,feasible_action_type,business_reason
25,SKU0014,FL,Florida DC,2026-W15,4,100939.0,224710.0,100939.0,224710.0,56177.500000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
6,SKU0006,FL,Florida DC,2026-W15,4,86445.0,178917.0,86445.0,178917.0,44729.250000,0,0.0,1,PA,Pennsylvania DC,160949.0,10.41,PA,Transfer Required,No timely STO or sufficient production support...
20,SKU0012,NV,Nevada DC,2026-W15,4,75080.0,162134.0,75080.0,162134.0,40533.500000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
9,SKU0007,NV,Nevada DC,2026-W15,4,58035.0,120649.0,58035.0,120649.0,30162.250000,0,0.0,1,PA,Pennsylvania DC,83074.0,8.19,PA,Transfer Required,No timely STO or sufficient production support...
38,SKU0020,NV,Nevada DC,2026-W15,4,68529.0,159073.0,68529.0,159073.0,39768.250000,0,0.0,1,PA,Pennsylvania DC,123128.0,10.29,PA,Transfer Required,No timely STO or sufficient production support...
16,SKU0009,NV,Nevada DC,2026-W15,4,94251.0,223670.0,94251.0,223670.0,55917.500000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
14,SKU0008,WA,Washington DC,2026-W15,4,76987.0,173280.0,76987.0,173280.0,43320.000000,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
19,SKU0012,FL,Florida DC,2026-W16,3,37629.0,62026.0,37629.0,62026.0,20675.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
28,SKU0017,FL,Florida DC,2026-W16,3,28899.0,48122.0,28899.0,48122.0,16040.666667,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
27,SKU0014,WA,Washington DC,2026-W16,3,52942.0,101726.0,52942.0,101726.0,33908.666667,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
26,SKU0014,TX,Texas DC,2026-W16,3,59964.0,109418.0,59964.0,109418.0,36472.666667,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
23,SKU0013,FL,Florida DC,2026-W16,3,26322.0,43627.0,26322.0,43627.0,14542.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
21,SKU0012,TX,Texas DC,2026-W16,3,53614.0,106526.0,53614.0,106526.0,35508.666667,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
17,SKU0009,TX,Texas DC,2026-W16,3,49695.0,89830.0,49695.0,89830.0,29943.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
15,SKU0009,FL,Florida DC,2026-W16,3,40170.0,65128.0,40170.0,65128.0,21709.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
12,SKU0008,FL,Florida DC,2026-W16,3,43261.0,68308.0,43261.0,68308.0,22769.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
32,SKU0018,FL,Florida DC,2026-W16,3,51095.0,86587.0,51095.0,86587.0,28862.333333,8733,0.0,1,PA,Pennsylvania DC,150698.0,12.23,PA,Transfer Required,No timely STO or sufficient production support...
35,SKU0019,FL,Florida DC,2026-W16,3,43058.0,80933.0,43058.0,80933.0,26977.666667,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
5,SKU0005,WA,Washington DC,2026-W16,3,29183.0,53596.0,29183.0,53596.0,17865.333333,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."
3,SKU0005,FL,Florida DC,2026-W16,3,37326.0,72455.0,37326.0,72455.0,24151.666667,0,0.0,0,None,None,0.0,NaN,None,No Feasible Source,"No timely STO, insufficient production support..."

In [269]:
# final recommendation
final_recommendation["feasible_action_type"].value_counts()

feasible_action_type
No Feasible Source       24
Transfer Required        13
Covered by Production     2
Covered by STO            1
Name: count, dtype: int64

In [271]:
final_recommendation[
    final_recommendation["feasible_action_type"] == "Transfer Required"
].head(20)

,sku_id,dc_id,dc_name,first_gap_week,total_gap_weeks,max_gap_qty_abs,cumulative_gap_qty_abs,qty_to_stabilize,qty_to_full_cover,avg_gap_per_gap_week,...,best_donor_dc_name,donor_surplus_qty,donor_wos,feasible_action_type,recommended_source,recommended_action,recommended_qty_stabilize,recommended_qty_full_cover,business_reason,action_priority
24,SKU0006,FL,Florida DC,2026-W15,4,86445.0,178917.0,86445.0,178917.0,44729.250000,...,Pennsylvania DC,160949.0,10.41,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,86445.0,160949.0,No timely STO or sufficient production support...,3
25,SKU0020,NV,Nevada DC,2026-W15,4,68529.0,159073.0,68529.0,159073.0,39768.250000,...,Pennsylvania DC,123128.0,10.29,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,68529.0,123128.0,No timely STO or sufficient production support...,3
26,SKU0007,NV,Nevada DC,2026-W15,4,58035.0,120649.0,58035.0,120649.0,30162.250000,...,Pennsylvania DC,83074.0,8.19,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,58035.0,83074.0,No timely STO or sufficient production support...,3
27,SKU0004,NV,Nevada DC,2026-W16,3,56319.0,110606.0,56319.0,110606.0,36868.666667,...,Pennsylvania DC,138719.0,11.20,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,56319.0,110606.0,No timely STO or sufficient production support...,3
28,SKU0018,FL,Florida DC,2026-W16,3,51095.0,86587.0,51095.0,86587.0,28862.333333,...,Pennsylvania DC,150698.0,12.23,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,51095.0,86587.0,No timely STO or sufficient production support...,3
29,SKU0020,WI,Wisconsin DC,2026-W18,1,11667.0,11667.0,11667.0,11667.0,11667.000000,...,Pennsylvania DC,123128.0,10.29,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,11667.0,11667.0,No timely STO or sufficient production support...,3
30,SKU0006,WI,Wisconsin DC,2026-W18,1,10068.0,10068.0,10068.0,10068.0,10068.000000,...,Pennsylvania DC,160949.0,10.41,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,10068.0,10068.0,No timely STO or sufficient production support...,3
31,SKU0006,TX,Texas DC,2026-W18,1,9974.0,9974.0,9974.0,9974.0,9974.000000,...,Pennsylvania DC,160949.0,10.41,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,9974.0,9974.0,No timely STO or sufficient production support...,3
32,SKU0018,WI,Wisconsin DC,2026-W18,1,8423.0,8423.0,8423.0,8423.0,8423.000000,...,Pennsylvania DC,150698.0,12.23,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,8423.0,8423.0,No timely STO or sufficient production support...,3
33,SKU0007,WI,Wisconsin DC,2026-W18,1,5908.0,5908.0,5908.0,5908.0,5908.000000,...,Pennsylvania DC,83074.0,8.19,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,5908.0,5908.0,No timely STO or sufficient production support...,3
34,SKU0007,TX,Texas DC,2026-W18,1,4423.0,4423.0,4423.0,4423.0,4423.000000,...,Pennsylvania DC,83074.0,8.19,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,4423.0,4423.0,No timely STO or sufficient production support...,3
35,SKU0004,WI,Wisconsin DC,2026-W18,1,1983.0,1983.0,1983.0,1983.0,1983.000000,...,Pennsylvania DC,138719.0,11.20,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,1983.0,1983.0,No timely STO or sufficient production support...,3
36,SKU0018,TX,Texas DC,2026-W18,1,1865.0,1865.0,1865.0,1865.0,1865.000000,...,Pennsylvania DC,150698.0,12.23,Transfer Required,PA,Transfer inventory from donor DC to shortage DC,1865.0,1865.0,No timely STO or sufficient production support...,3

In [273]:
final_recommendation[
    final_recommendation["feasible_action_type"] == "Partial Transfer / Escalate"
].head(20)

Empty DataFrame
Columns: [sku_id, dc_id, dc_name, first_gap_week, total_gap_weeks, max_gap_qty_abs, cumulative_gap_qty_abs, qty_to_stabilize, qty_to_full_cover, avg_gap_per_gap_week, sto_can_cover_qty, production_can_cover_qty, donor_exists, best_donor_dc, best_donor_dc_name, donor_surplus_qty, donor_wos, feasible_action_type, recommended_source, recommended_action, recommended_qty_stabilize, recommended_qty_full_cover, business_reason, action_priority]
Index: []

[0 rows x 24 columns]

In [275]:
gap_summary["severity"] = pd.cut(
    gap_summary["cumulative_gap_qty_abs"],
    bins=[0, 50000, 150000, 999999999],
    labels=["Low", "Medium", "High"]
)

In [277]:
from pathlib import Path
import pandas as pd

powerbi_path = project_root / "output" / "powerbi"
powerbi_path.mkdir(parents=True, exist_ok=True)

# -----------------------------
# 1. dim_sku
# -----------------------------
dim_sku = product_master.copy()

dim_sku = dim_sku[[
    "sku_id",
    "sku_desc",
    "brand",
    "report_size",
    "product_type",
    "flavor",
    "pack_type",
    "shelf_life_days",
    "is_active"
]].drop_duplicates()

# -----------------------------
# 2. dim_dc
# -----------------------------
dim_dc = pd.DataFrame([
    {"dc_id": "PA", "dc_name": "Pennsylvania DC", "region_group": "East",    "coast_group": "East",   "dc_sort": 1},
    {"dc_id": "TX", "dc_name": "Texas DC",        "region_group": "South",   "coast_group": "Central","dc_sort": 2},
    {"dc_id": "FL", "dc_name": "Florida DC",      "region_group": "South",   "coast_group": "East",   "dc_sort": 3},
    {"dc_id": "NV", "dc_name": "Nevada DC",       "region_group": "West",    "coast_group": "West",   "dc_sort": 4},
    {"dc_id": "WI", "dc_name": "Wisconsin DC",    "region_group": "Midwest", "coast_group": "Central","dc_sort": 5},
    {"dc_id": "WA", "dc_name": "Washington DC",   "region_group": "West",    "coast_group": "West",   "dc_sort": 6},
])

# -----------------------------
# 3. fact_gap_summary
# -----------------------------
fact_gap_summary = gap_summary.copy()

fact_gap_summary["severity_label"] = pd.cut(
    fact_gap_summary["cumulative_gap_qty_abs"],
    bins=[-1, 50000, 150000, float("inf")],
    labels=["Low", "Medium", "High"]
)

week_sort_map = {
    "2026-W15": 15,
    "2026-W16": 16,
    "2026-W17": 17,
    "2026-W18": 18,
}
fact_gap_summary["first_gap_week_sort"] = fact_gap_summary["first_gap_week"].map(week_sort_map)

fact_gap_summary = fact_gap_summary[[
    "sku_id",
    "dc_id",
    "dc_name",
    "first_gap_week",
    "first_gap_week_sort",
    "total_gap_weeks",
    "max_gap_qty_abs",
    "cumulative_gap_qty_abs",
    "severity_label"
]]

# -----------------------------
# 4. fact_replenishment_feasibility
# -----------------------------
fact_replenishment_feasibility = replenishment_feasibility.copy()

# 统一字段名，方便和 dim_dc 关系
fact_replenishment_feasibility = fact_replenishment_feasibility.rename(columns={
    "shortage_dc": "dc_id",
    "shortage_dc_name": "dc_name"
})

fact_replenishment_feasibility = fact_replenishment_feasibility[[
    "sku_id",
    "dc_id",
    "dc_name",
    "first_gap_week",
    "qty_to_stabilize",
    "qty_to_full_cover",
    "avg_gap_per_gap_week",
    "sto_can_cover_qty",
    "production_can_cover_qty",
    "donor_exists",
    "best_donor_dc",
    "best_donor_dc_name",
    "donor_surplus_qty",
    "donor_wos",
    "feasible_action_type",
    "business_reason"
]]

# -----------------------------
# 5. fact_recommendation
# -----------------------------
fact_recommendation = final_recommendation.copy()

fact_recommendation = fact_recommendation[[
    "sku_id",
    "dc_id",
    "dc_name",
    "first_gap_week",
    "total_gap_weeks",
    "max_gap_qty_abs",
    "cumulative_gap_qty_abs",
    "qty_to_stabilize",
    "qty_to_full_cover",
    "avg_gap_per_gap_week",
    "sto_can_cover_qty",
    "production_can_cover_qty",
    "donor_exists",
    "best_donor_dc",
    "best_donor_dc_name",
    "donor_surplus_qty",
    "donor_wos",
    "feasible_action_type",
    "recommended_source",
    "recommended_action",
    "recommended_qty_stabilize",
    "recommended_qty_full_cover",
    "business_reason",
    "action_priority"
]]

# -----------------------------
# 6. fact_weekly_projection
# -----------------------------
fact_weekly_projection = weekly_inventory_projection.copy()

fact_weekly_projection["week_sort"] = fact_weekly_projection["week"].map(week_sort_map)

fact_weekly_projection = fact_weekly_projection[[
    "sku_id",
    "dc_id",
    "dc_name",
    "week",
    "week_sort",
    "beginning_inventory",
    "forecast_qty",
    "inbound_sto_qty",
    "inbound_production_qty",
    "projected_ending_inventory",
    "projected_wos",
    "gap_flag"
]]

# -----------------------------
# Export all CSVs
# -----------------------------
dim_sku.to_csv(powerbi_path / "dim_sku.csv", index=False)
dim_dc.to_csv(powerbi_path / "dim_dc.csv", index=False)
fact_gap_summary.to_csv(powerbi_path / "fact_gap_summary.csv", index=False)
fact_replenishment_feasibility.to_csv(powerbi_path / "fact_replenishment_feasibility.csv", index=False)
fact_recommendation.to_csv(powerbi_path / "fact_recommendation.csv", index=False)
fact_weekly_projection.to_csv(powerbi_path / "fact_weekly_projection.csv", index=False)

print("Power BI files exported to:", powerbi_path)
for f in sorted(powerbi_path.glob("*.csv")):
    print("-", f.name)

Power BI files exported to: /Users/yizhen/Inventory_rebalancing_project/output/powerbi
- dim_dc.csv
- dim_sku.csv
- fact_gap_summary.csv
- fact_recommendation.csv
- fact_replenishment_feasibility.csv
- fact_weekly_projection.csv